import type { Rules, ScoreInput, Side, PointLog } from "./types.js";
import { ensure } from "./types.js";
export interface LiveState {sets:ScoreInput[];wins:[number,number];games:[number,number];points:[number,number];winner:Side|null;pointCount:number}
export const initialScore=():LiveState=>({sets:[],wins:[0,0],games:[0,0],points:[0,0],winner:null,pointCount:0});
export const isPointSet=(r:Rules)=>["tiebreak_7","points_11","points_15"].includes(r.scoring_type);
export const gameTarget=(r:Rules)=>r.scoring_type==="games_4"?4:r.scoring_type==="games_6"?6:r.custom_games_target!;
export const tieTrigger=(r:Rules)=>r.scoring_type==="custom_games"?r.custom_games_target!:r.tiebreak_trigger!;
export const pointTarget=(r:Rules)=>r.scoring_type==="points_11"?11:r.scoring_type==="points_15"?15:7;
export const currentSetNumber=(s:LiveState)=>s.sets.length+1;
export const currentGameNumber=(s:LiveState)=>s.games[0]+s.games[1]+1;
export const contextFor=(r:Rules,s:LiveState):PointLog["scoring_context"]=>isPointSet(r)?"point_set":s.games[0]===tieTrigger(r)&&s.games[1]===tieTrigger(r)?"tiebreak":"normal_game";
function reached(a:number,b:number,target:number){return Math.max(a,b)>=target&&Math.abs(a-b)>=2}
function normalGameWon(r:Rules,a:number,b:number){return r.game_scoring==="no_ad"?Math.max(a,b)>=4&&Math.min(a,b)<=3:reached(a,b,4)}
function validPointEnd(a:number,b:number,target:number){const hi=Math.max(a,b),lo=Math.min(a,b);return(hi===target&&lo<=target-2)||(hi>target&&hi-lo===2)}
export function setWinner(r:Rules,score:ScoreInput):Side{const{a,b,ta,tb}=score;ensure([a,b].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=100000),"SCORE_INTEGER","比分必须是非负整数");ensure(a!==b,"SET_INCOMPLETE","本盘尚未决出胜者");if(isPointSet(r)){ensure(ta==null&&tb==null,"EXTRA_TIEBREAK","连续抢分盘不另填抢七小分");ensure(validPointEnd(a,b,pointTarget(r)),"POINT_SET_INVALID","抢分必须达到目标并领先2分，结束后不能继续加分");return a>b?"A":"B"}const hi=Math.max(a,b),lo=Math.min(a,b),target=gameTarget(r),trigger=tieTrigger(r);if(hi===trigger+1&&lo===trigger){ensure(ta!=null&&tb!=null,"TIEBREAK_REQUIRED","请补全抢七小分");ensure([ta,tb].every(n=>Number.isSafeInteger(n)&&n>=0&&n<=100000)&&validPointEnd(ta,tb,7),"TIEBREAK_INVALID","抢七必须先到7分且领先2分");ensure(ta>tb===a>b,"TIEBREAK_WINNER","抢七胜方必须与本盘胜方一致")}else{ensure(ta==null&&tb==null,"EXTRA_TIEBREAK","这盘没有发生抢七，不应填写抢七小分");ensure((hi===target&&lo<=target-2)||(hi===target+1&&lo===target-1&&trigger===target),"GAMES_INVALID","局分不符合本场目标局数和抢七触发规则")}return a>b?"A":"B"}
export function validateFinalScore(r:Rules,scores:ScoreInput[]):Side{ensure(scores.length>=1&&scores.length<=r.best_of,"SET_COUNT","盘数与比赛规则不符");const wins=[0,0],needed=(r.best_of+1)/2;for(const score of scores){ensure(Math.max(...wins)<needed,"EXTRA_SET","比赛已结束，不能再填写多余盘");wins[setWinner(r,score)==="A"?0:1]++}ensure(Math.max(...wins)===needed,"MATCH_INCOMPLETE","尚未达到所需胜盘数");return wins[0]>wins[1]?"A":"B"}
function finishSet(r:Rules,s:LiveState,score:ScoreInput,side:Side){s.sets.push(score);s.wins[side==="A"?0:1]++;s.games=[0,0];s.points=[0,0];if(s.wins[side==="A"?0:1]===(r.best_of+1)/2)s.winner=side}
export function addPoint(r:Rules,previous:LiveState,side:Side):LiveState{ensure(!previous.winner,"MATCH_FINISHED","比赛已结束，请使用比分更正");ensure(side==="A"||side==="B","SIDE","请选择得分方");const s:LiveState={...previous,sets:previous.sets.map(x=>({...x})),wins:[...previous.wins],games:[...previous.games],points:[...previous.points],pointCount:previous.pointCount+1};const context=contextFor(r,s),i=side==="A"?0:1;s.points[i]++;if(context==="normal_game"){if(normalGameWon(r,s.points[0],s.points[1])){s.games[i]++;s.points=[0,0];if(reached(...s.games,gameTarget(r)))finishSet(r,s,{a:s.games[0],b:s.games[1]},side)}}else if(reached(...s.points,context==="tiebreak"?7:pointTarget(r))){if(context==="tiebreak"){s.games[i]++;finishSet(r,s,{a:s.games[0],b:s.games[1],ta:s.points[0],tb:s.points[1]},side)}else finishSet(r,s,{a:s.points[0],b:s.points[1]},side)}return s}
export function replay(r:Rules,logs:Pick<PointLog,"winner_side"|"voided_at"|"point_no">[]):LiveState{return logs.filter(l=>!l.voided_at).slice().sort((a,b)=>a.point_no-b.point_no).reduce((s,l)=>addPoint(r,s,l.winner_side),initialScore())}
export function displayPoints(r:Rules,s:LiveState):{a:string;b:string;label:string}{if(s.winner)return{a:String(s.wins[0]),b:String(s.wins[1]),label:"比赛结束"};const context=contextFor(r,s);if(context!=="normal_game")return{a:String(s.points[0]),b:String(s.points[1]),label:context==="tiebreak"?"抢七":"连续抢分"};const[a,b]=s.points;if(a===3&&b===3&&r.game_scoring==="no_ad")return{a:"40",b:"40",label:"平分 · 金球"};if(a>=3&&b>=3){if(a===b)return{a:"40",b:"40",label:"Deuce · 平分"};return{a:a>b?"AD":"40",b:b>a?"AD":"40",label:"Advantage · 占先"}}return{a:String([0,15,30,40][Math.min(a,3)]),b:String([0,15,30,40][Math.min(b,3)]),label:"当前分"}}
