import { useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Plus, ArrowRight, Share2 } from "lucide-react";
import { Avatar, Header, Loading, Empty, ErrorNotice, Sheet } from "../components/UI";
import { repository, rpc, explainError } from "../repositories/supabase";
import { useAuth } from "../hooks/Auth";
import { useQuery } from "../hooks/useQuery";
type Connection={connection_id:string;id:string;nickname:string|null;avatar_url:string|null;created_at:string};type Invite={id:string;nickname:string|null;avatar_url:string|null;relationship_status:"self"|"accepted"|"pending"|"rejected"|"none"};
export function ConnectionsPage(){const {profile}=useAuth();const [sheet,setSheet]=useState(false),[feedback,setFeedback]=useState("");const connections=useQuery("connections",()=>rpc<Connection[]>("list_connections"),15000);const players=useQuery("players-social",()=>repository.players(),15000);const manual=players.data?.filter(p=>p.player_type==="manual")||[];async function shareInvite(){if(!profile?.id)return;const url=`${window.location.origin}${window.location.pathname}#/connect/${profile.id}`,text=`${profile.nickname||"你的朋友"} 邀请你成为球搭子`;try{if(navigator.share)await navigator.share({title:"球搭子邀请",text,url});else{await navigator.clipboard.writeText(url);setFeedback("邀请链接已复制")}setSheet(false)}catch(e){if((e as Error).name!=="AbortError")setFeedback("分享失败，请重试")}}return <><Header title="球搭子们" back={false} action={<button className="icon-button" aria-label="添加" onClick={()=>setSheet(true)}><Plus/></button>}/><main className="page"><span className="eyebrow">YOUR TENNIS PEOPLE</span><h1>球搭子们</h1>{feedback&&<div className="notice">{feedback}</div>}<div className="section-heading"><h2>我的球搭子</h2></div><ErrorNotice message={connections.error} retry={connections.refresh}/>{connections.loading&&!connections.data?<Loading/>:connections.data?.length?connections.data.map(c=><div className="card row" key={c.connection_id}><Avatar path={c.avatar_url} name={c.nickname||"球搭子"}/><strong className="grow">{c.nickname||"球搭子"}</strong></div>):<Empty title="还没有球搭子"><p>和一起打球的人保持联系，下次约球会更方便。</p><button onClick={()=>setSheet(true)}>添加球搭子</button></Empty>}<Link className="card row between" to="/players/new"><div><strong>临时参赛者</strong><p className="muted small">{manual.length?`${manual.length} 人`:"还没有录入"} · 仅用于帮你组织比赛</p></div><ArrowRight size={18}/></Link>{manual.map(p=><Link className="card row" to={`/players/${p.id}/edit`} key={p.id}><Avatar path={p.avatar_url} name={p.name}/><span className="grow">{p.name}</span><span className="badge">临时</span></Link>)}</main><Sheet open={sheet} title="添加" onClose={()=>setSheet(false)}><button className="action-row" onClick={shareInvite}><Share2/><span className="action-copy"><strong>邀请球搭子</strong><small>通过邀请链接，让朋友成为你的球搭子</small></span><ArrowRight size={18}/></button><Link className="action-row" to="/players/new" onClick={()=>setSheet(false)}><Plus/><span className="action-copy"><strong>添加临时参赛者</strong><small>朋友还没使用球搭子？先帮 TA 参加比赛</small></span><ArrowRight size={18}/></Link></Sheet></>}
export function ConnectionInvitePage(){const {inviterId}=useParams();const navigate=useNavigate();const [busy,setBusy]=useState(false),[error,setError]=useState("");const q=useQuery("connection-invite-"+inviterId,()=>rpc<Invite>("get_connection_invite",{p_inviter_profile_id:inviterId}),15000);async function accept(){if(!inviterId)return;setBusy(true);setError("");try{await rpc("accept_connection_invite",{p_inviter_profile_id:inviterId});await q.refresh()}catch(e){setError(explainError(e))}finally{setBusy(false)}}if(q.loading&&!q.data)return <><Header title="球搭子邀请"/><main className="page"><Loading/></main></>;const i=q.data;return <><Header title="球搭子邀请"/><main className="page profile-page"><ErrorNotice message={q.error||error}/>{i&&<><Avatar path={i.avatar_url} name={i.nickname||"球搭子"} size={92}/><span className="eyebrow">LET'S PLAY TOGETHER</span><h1>{i.nickname||"一位朋友"}<br/>邀请你成为球搭子</h1><p className="muted">成为球搭子后，你们会出现在彼此的球搭子列表里。</p>{i.relationship_status==="self"?<button className="full" onClick={()=>navigate("/players")}>这是我的邀请链接</button>:i.relationship_status==="accepted"?<button className="full" onClick={()=>navigate("/players")}>已经是球搭子 · 查看列表</button>:<button className="full" disabled={busy} onClick={accept}>{busy?"正在添加…":"加为球搭子"}</button>}</>}</main></>}
