import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import type { EventConfig } from "../domain/types";
import { validateEvent } from "../domain/EventRules";
import { explainError, repository } from "../repositories/supabase";
import { invalidateQueryPrefix } from "../hooks/useQuery";
import { Confirm, ErrorNotice, Header, labels } from "../components/UI";

const initial:EventConfig={name:"",visibility:"public",link_signup_enabled:true,match_type:"singles",format:"round_robin",best_of:1,scoring_type:"games_6",custom_games_target:null,tiebreak_trigger:6,level:null,entry_limit:8,event_date:null,event_time:null,city:null,venue:null,fee_type:"free",venue_fee_total:null,ball_fee_total:null,other_fee_total:null,fixed_fee_per_entry:null,group_count:2,qualifiers_per_group:2};
const levelOptions:[[string,string]]|[string,string][]=[["≤2.0","2.0及以下"],["2.5","2.5"],["3.0","3.0"],["3.5","3.5"],["4.0","4.0"],["≥4.5","4.5及以上"]];
export function EventFormPage(){
  const{id}=useParams(),navigate=useNavigate();const[deleteConfirm,setDeleteConfirm]=useState(false);const[form,setForm]=useState<EventConfig>(initial),[version,setVersion]=useState<number>(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[section,setSection]=useState(0);
  useEffect(()=>{if(id)repository.event(id).then(s=>{const c={...initial};Object.keys(c).forEach(k=>((c as any)[k]=(s.event as any)[k]));setForm(c);setVersion(s.event.version);}).catch(e=>setError(explainError(e)));},[id]);
  function set(k:keyof EventConfig,v:unknown){setForm(f=>({...f,[k]:v,...(k==="scoring_type"?{tiebreak_trigger:v==="games_4"?4:v==="games_6"?6:null}:{})}));}
  function field(k:keyof EventConfig,label:string,type="text",options?:[string,string][]){return <label key={k}>{label}{options?<select value={String(form[k]??"")} onChange={e=>set(k,k==="best_of"||k==="tiebreak_trigger"?Number(e.target.value):e.target.value||null)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input type={type} value={String(form[k]??"")} onChange={e=>set(k,type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value||null)} step={type==="number"?"any":undefined} maxLength={k==="name"?80:k==="city"?30:120}/>}</label>;}
  async function save(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);try{const config=validateEvent({...form,name:form.name||""});const result=await repository.saveEvent(id||null,config,version);invalidateQueryPrefix("events");navigate("/events/"+result.id+"/manage",{replace:true});}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  const sections=[
    {title:"赛事基础",body:<>{field("name","赛事名称 *")}{field("visibility","赛事可见范围 *","text",[["public","公开 · 所有用户可见"],["private","私有 · 仅被邀请人可见"]])}<p className="muted small">公开赛事会出现在赛事大厅；私有赛事不会出现在大厅，只有组织者和被邀请的用户可以查看。</p>{field("match_type","比赛类型","text",[["singles","单打"],["doubles","双打"]])}{field("format","赛制","text",[["round_robin","单循环"],["knockout","单淘汰"],["group_knockout","小组 + 淘汰"]])}</>},
    {title:"比赛规则",body:<>{field("best_of","盘数","text",[["1","一盘决胜"],["3","三盘两胜"],["5","五盘三胜"]])}{field("scoring_type","每盘计分","text",Object.entries(labels).filter(([k])=>["games_4","games_6","tiebreak_7","points_11","points_15","custom_games"].includes(k)) as [string,string][])}{form.scoring_type==="games_4"&&field("tiebreak_trigger","抢七触发","text",[["3","3:3"],["4","4:4"]])}{form.scoring_type==="games_6"&&field("tiebreak_trigger","抢七触发","text",[["5","5:5"],["6","6:6"]])}{form.scoring_type==="custom_games"&&field("custom_games_target","目标局数 ≥1","number")}<p className="muted small">传统占先制。抢七和连续抢分均需领先2分。</p>{form.format==="group_knockout"&&<>{field("group_count","小组数量","number")}{field("qualifiers_per_group","每组晋级名额","number")}</>}</>},
    {title:"时间与场地",body:<>{field("level","赛事级别（可选）","text",[["","不限定"],...levelOptions])}{field("entry_limit","名额上限（"+(form.match_type==="doubles"?"队":"人")+"）","number")}{field("event_date","比赛日期（可选）","date")}{field("event_time","比赛时间（可选）","time")}{field("city","城市 *")}{field("venue","比赛场地（可选）")}<p className="muted small">城市为必填项，会和赛事级别一起直接显示在赛事卡片上。</p></>},
    {title:"费用说明",body:<>{field("fee_type","费用类型","text",[["free","免费"],["aa","AA制"],["fixed","固定费用"]])}{form.fee_type==="aa"&&<>{field("venue_fee_total","场地总费用（元）","number")}{field("ball_fee_total","用球总费用（元）","number")}{field("other_fee_total","其他总费用（元）","number")}<div className="notice">预计总费用 ¥{(form.venue_fee_total||0)+(form.ball_fee_total||0)+(form.other_fee_total||0)}<br/>按实际正式参赛{form.match_type==="doubles"?"队伍":"人数"}均摊。</div></>}{form.fee_type==="fixed"&&field("fixed_fee_per_entry","每"+(form.match_type==="doubles"?"队":"人")+"费用（元）","number")}<p className="muted small">费用仅展示，不提供在线支付和退款。</p></>},
  ];
  return <><Header title={id?"编辑赛事":"创建赛事"}/><main className="page has-action"><span className="eyebrow">YOUR NEXT MATCH</span><h1>{id?"调整比赛安排":"发起一场好球"}</h1><p className="muted">先集结球搭子，再锁定名单生成对阵。</p><form onSubmit={save}>{sections.map((s,i)=><section className="form-section" key={s.title}><button type="button" className="section-toggle" onClick={()=>setSection(i)}><span className="section-number">0{i+1}</span><strong>{s.title}</strong><span>{section===i?"−":"＋"}</span></button>{section===i&&<div className="section-body">{s.body}{i<3&&<button type="button" className="secondary full" onClick={()=>setSection(i+1)}>继续设置</button>}</div>}</section>)}<ErrorNotice message={error}/>{id&&<button type="button" className="danger full" disabled={busy} onClick={()=>setDeleteConfirm(true)}>删除空赛事</button>}<div className="action-bar"><button className="full" disabled={busy}>{busy?"保存中…":id?"保存修改":"创建赛事"}</button></div></form></main>{deleteConfirm&&<Confirm title="删除这场赛事？" description="仅报名中且没有任何报名历史的空赛事可删除，已有报名记录的赛事将被保护。" busy={busy} onCancel={()=>setDeleteConfirm(false)} onConfirm={async()=>{setBusy(true);try{await repository.deleteEvent(id!,version!);invalidateQueryPrefix("events");navigate("/my-events");}catch(e){setError(explainError(e));setDeleteConfirm(false);}finally{setBusy(false);}}}/>}</>;
}
