import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import type { EventConfig } from "../domain/types";
import { defaultRegistrationDeadline, validateEvent } from "../domain/EventRules";
import { explainError, repository } from "../repositories/supabase";
import { invalidateQueryPrefix } from "../hooks/useQuery";
import { Confirm, ErrorNotice, Header, labelFor, levelLabel } from "../components/UI";
import { useLanguage } from "../i18n";

const initial:EventConfig={name:"",visibility:"public",link_signup_enabled:true,match_type:"singles",format:"round_robin",best_of:1,scoring_type:"games_6",custom_games_target:null,tiebreak_trigger:6,level:null,suggested_level_min:null,suggested_level_max:null,entry_limit:8,event_date:null,event_time:null,registration_deadline:null,city:null,venue:null,fee_type:"free",venue_fee_total:null,ball_fee_total:null,other_fee_total:null,fixed_fee_per_entry:null,group_count:2,qualifiers_per_group:2};
export function EventFormPage(){
  const{id}=useParams(),navigate=useNavigate();const{language,t}=useLanguage();const[deleteConfirm,setDeleteConfirm]=useState(false);const[form,setForm]=useState<EventConfig>(initial),[version,setVersion]=useState<number>(),[error,setError]=useState(""),[busy,setBusy]=useState(false),[section,setSection]=useState(0),[deadlineAdjusted,setDeadlineAdjusted]=useState(false),[deadlineMode,setDeadlineMode]=useState<"auto"|"manual">("auto");
  const levelOptions:[string,string][]=[["≤2.0",levelLabel("≤2.0",language)],["2.5","2.5"],["3.0","3.0"],["3.5","3.5"],["4.0","4.0"],["≥4.5",levelLabel("≥4.5",language)]];
  useEffect(()=>{if(id)repository.event(id).then(s=>{const c={...initial};Object.keys(c).forEach(k=>((c as any)[k]=(s.event as any)[k]));if(!c.suggested_level_min&&!c.suggested_level_max&&s.event.level){c.suggested_level_min=s.event.level==="≤2.0"?null:s.event.level;c.suggested_level_max=s.event.level==="≥4.5"?null:s.event.level;}const latest=defaultRegistrationDeadline(c.event_date,c.event_time);setDeadlineMode(c.registration_deadline&&latest&&c.registration_deadline!==latest?"manual":"auto");setForm(c);setVersion(s.event.version);}).catch(e=>setError(explainError(e)));},[id]);
  function set(k:keyof EventConfig,v:unknown){setForm(f=>{const next={...f,[k]:v,...(k==="scoring_type"?{tiebreak_trigger:v==="games_4"?4:v==="games_6"?6:null}:{})};if(k==="registration_deadline"){setDeadlineAdjusted(false);if(!v){next.registration_deadline=defaultRegistrationDeadline(next.event_date,next.event_time);setDeadlineMode("auto");}else setDeadlineMode("manual");return next;}if(k==="event_date"||k==="event_time"){const latest=defaultRegistrationDeadline(next.event_date,next.event_time);if(latest){if(deadlineMode==="auto"||!next.registration_deadline){next.registration_deadline=latest;setDeadlineAdjusted(false);}else if(next.registration_deadline>latest){next.registration_deadline=latest;setDeadlineAdjusted(true);}}}return next;});}
  function field(k:keyof EventConfig,label:string,type="text",options?:[string,string][]){return <label key={k}>{label}{options?<select value={String(form[k]??"")} onChange={e=>set(k,k==="best_of"||k==="tiebreak_trigger"?Number(e.target.value):e.target.value||null)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input type={type} value={String(form[k]??"")} onChange={e=>set(k,type==="number"?(e.target.value===""?null:Number(e.target.value)):e.target.value||null)} step={type==="number"?"any":undefined} maxLength={k==="name"?80:k==="city"?30:120}/>}</label>;}
  async function save(e:React.FormEvent){e.preventDefault();setError("");setBusy(true);try{const config=validateEvent({...form,name:form.name||""});const result=await repository.saveEvent(id||null,config,version);invalidateQueryPrefix("events");navigate("/events/"+result.id+"/manage",{replace:true});}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  const latestDeadline=defaultRegistrationDeadline(form.event_date,form.event_time);
  const sections=[
    {title:t("eventBasics"),body:<>{field("name",t("eventName"))}{field("visibility",t("visibility"),"text",[["public",t("publicFull")],["private",t("privatePreview")]])}<p className="muted small">{t("visibilityHint")}</p>{field("match_type",t("matchType"),"text",[["singles",t("singles")],["doubles",t("doubles")]])}{field("format",t("format"),"text",[["round_robin",t("roundRobin")],["knockout",t("knockout")],["group_knockout",t("groupKnockout")]])}<div className="row form-pair">{field("suggested_level_min",t("suggestedMin"),"text",[["",t("unlimited")],...levelOptions])}{field("suggested_level_max",t("suggestedMax"),"text",[["",t("unlimited")],...levelOptions])}</div><p className="muted small">{t("suggestedHint")}</p></>},
    {title:t("matchRules"),body:<>{field("best_of",t("sets"),"text",[["1",t("oneSet")],["3",t("bestOfThree")],["5",t("bestOfFive")]])}{field("scoring_type",t("scoringPerSet"),"text",["games_4","games_6","tiebreak_7","points_11","points_15","custom_games"].map(k=>[k,labelFor(k,language)]) as [string,string][])}{form.scoring_type==="games_4"&&field("tiebreak_trigger",t("tiebreakTrigger"),"text",[["3","3:3"],["4","4:4"]])}{form.scoring_type==="games_6"&&field("tiebreak_trigger",t("tiebreakTrigger"),"text",[["5","5:5"],["6","6:6"]])}{form.scoring_type==="custom_games"&&field("custom_games_target",t("targetGames"),"number")}<p className="muted small">{t("scoringHint")}</p>{form.format==="group_knockout"&&<>{field("group_count",t("groupCount"),"number")}{field("qualifiers_per_group",t("qualifiersPerGroup"),"number")}</>}</>},
    {title:t("timeVenue"),body:<>{field("entry_limit",`${t("entryLimit")} (${form.match_type==="doubles"?(language==="en"?"teams":"队"):(language==="en"?"players":"人")})`,"number")}{field("event_date",language==="en"?"Match date *":"比赛日期 *","date")}{field("event_time",t("startTime"),"time")}{field("registration_deadline",t("latestRegistration"),"datetime-local")}{deadlineAdjusted&&<div className="notice">{t("deadlineAdjusted")}</div>}<p className="muted small">{t("deadlineRule")}{latestDeadline?` ${t("currentLatest")} ${latestDeadline.replace("T"," ")}`:""}</p>{field("city",t("eventCity"))}{field("venue",t("optionalVenue"))}<p className="muted small">{t("timeVenueHint")}</p></>},
    {title:t("feeInfo"),body:<>{field("fee_type",t("feeType"),"text",[["free",t("free")],["aa",t("aa")],["fixed",t("fixedFee")]])}{form.fee_type==="aa"&&<>{field("venue_fee_total",t("venueFee"),"number")}{field("ball_fee_total",t("ballFee"),"number")}{field("other_fee_total",t("otherFee"),"number")}<div className="notice">{t("estimatedTotal")} ¥{(form.venue_fee_total||0)+(form.ball_fee_total||0)+(form.other_fee_total||0)}<br/>{form.match_type==="doubles"?t("splitByTeams"):t("splitByParticipants")}</div></>}{form.fee_type==="fixed"&&field("fixed_fee_per_entry",form.match_type==="doubles"?t("perTeamFee"):t("perPlayerFee"),"number")}<p className="muted small">{t("feeHint")}</p></>},
  ];
  return <><Header title={id?t("editEvent"):t("createEvent")}/><main className="page has-action"><span className="eyebrow">{t("eventSetup")}</span><h1>{id?t("adjustMatch"):t("startGoodMatch")}</h1><p className="muted">{t("formHeroHint")}</p><form onSubmit={save}>{sections.map((s,i)=><section className="form-section" key={s.title}><button type="button" className="section-toggle" onClick={()=>setSection(i)}><span className="section-number">0{i+1}</span><strong>{s.title}</strong><span>{section===i?"−":"＋"}</span></button>{section===i&&<div className="section-body">{s.body}{i<3&&<button type="button" className="secondary full" onClick={()=>setSection(i+1)}>{t("continueSetup")}</button>}</div>}</section>)}<ErrorNotice message={error}/>{id&&<button type="button" className="danger full" disabled={busy} onClick={()=>setDeleteConfirm(true)}>{t("deleteEmptyEvent")}</button>}<div className="action-bar"><button className="full" disabled={busy}>{busy?t("savingChanges"):id?t("saveChanges"):t("createEvent")}</button></div></form></main>{deleteConfirm&&<Confirm title={t("deleteEventTitle")} description={t("deleteEventDescription")} busy={busy} onCancel={()=>setDeleteConfirm(false)} onConfirm={async()=>{setBusy(true);try{await repository.deleteEvent(id!,version!);invalidateQueryPrefix("events");navigate("/my-events");}catch(e){setError(explainError(e));setDeleteConfirm(false);}finally{setBusy(false);}}}/>}</>;
}
