import { useCallback, useEffect, useState } from "react";
import { Download, Eye, X } from "lucide-react";
import { Header, ErrorNotice, Loading, Empty, Confirm } from "../components/UI";
import { explainError, rpc, supabase } from "../repositories/supabase";
import { useLanguage } from "../i18n";
import { savePhotoToDevice } from "../utils/photoSave";

type AlbumPhoto={asset_id:string;event_id:string;event_name:string;event_date:string|null;uploaded_at:string};

export function MyPastAlbumsPage(){
  const{language}=useLanguage();const en=language==="en";
  const[rows,setRows]=useState<AlbumPhoto[]|null>(null),[urls,setUrls]=useState<Record<string,string>>({}),[hd,setHd]=useState<{assetId:string;url:string;eventName:string}|null>(null),[busy,setBusy]=useState<string>(),[deleting,setDeleting]=useState<AlbumPhoto|null>(null),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const data=await rpc<AlbumPhoto[]>("list_my_past_event_albums");setRows(data);setUrls({});for(const row of data){const{data:preview,error:invokeError}=await supabase!.functions.invoke("photo-management",{body:{action:"personal_preview",asset_id:row.asset_id}});if(!invokeError&&preview?.url)setUrls(v=>({...v,[row.asset_id]:preview.url}));}}catch(e){setError(explainError(e));}},[]);
  useEffect(()=>{void load();},[load]);
  async function personalOriginalUrl(assetId:string){const{data,error:invokeError}=await supabase!.functions.invoke("photo-management",{body:{action:"personal_original",asset_id:assetId}});if(invokeError)throw invokeError;if(!data?.url)throw new Error(en?"This photo is not available right now.":"当前照片暂不可用。");return data.url as string;}
  async function openHd(photo:AlbumPhoto){setBusy(photo.asset_id);setError("");try{const url=await personalOriginalUrl(photo.asset_id);setHd({assetId:photo.asset_id,url,eventName:photo.event_name});}catch(e){setError(explainError(e));}finally{setBusy(undefined);}}
  async function save(photo:AlbumPhoto){setBusy(photo.asset_id);setError("");try{const url=await personalOriginalUrl(photo.asset_id);await savePhotoToDevice(url,`${photo.event_name}-saved-photo.jpg`);}catch(e){setError(explainError(e));}finally{setBusy(undefined);}}
  async function remove(photo:AlbumPhoto){setDeleting(null);setBusy(photo.asset_id);setError("");try{const{error:invokeError}=await supabase!.functions.invoke("photo-management",{body:{action:"delete_personal",asset_id:photo.asset_id}});if(invokeError)throw invokeError;await load();}catch(e){setError(explainError(e));}finally{setBusy(undefined);}}
  const events=[...new Set((rows||[]).map(r=>r.event_id))];
  return <><Header title={en?"My event album":"参与赛事相册"}/><main className="page">
    <span className="eyebrow">{en?"YOUR SAVED MATCH MEMORIES":"我的比赛记忆"}</span><h1>{en?"My event album":"参与赛事相册"}</h1>
    <p className="muted">{en?"Only photos you personally chose from events you actually played in appear here. Once imported, your copy remains even if the organizer later deletes the source event photo.":"这里只有你从自己实际参加的赛事中主动加入的照片。导入成功后就是你的独立个人相册资产，即使赛事创建人之后删除源照片，你已经保存的照片也不会消失。"}</p>
    <ErrorNotice message={error}/>{rows===null?<Loading/>:rows.length===0?<Empty title={en?"No saved event photos yet":"还没有保存赛事照片"}><p>{en?"Open an event you played in and add the photos you want to keep.":"进入你实际参加过的赛事相册，逐张选择“加入我的参与赛事相册”。"}</p></Empty>:events.map(eventId=>{const photos=rows.filter(r=>r.event_id===eventId);const first=photos[0];return <section className="settings-section" key={eventId}><div className="section-heading"><div><h2>{first.event_name}</h2><p className="muted small">{first.event_date||new Date(first.uploaded_at).toLocaleDateString(en?"en-US":"zh-CN")}</p></div></div><div className="personal-album-grid">{photos.map(photo=><article className="personal-album-card" key={photo.asset_id}>{urls[photo.asset_id]?<img className="personal-album-thumb" src={urls[photo.asset_id]} alt={first.event_name}/>:<div className="personal-album-thumb photo-frame-preview"><span>{en?"Loading protected preview…":"正在加载受保护预览…"}</span></div>}<div className="personal-album-actions"><button className="secondary personal-album-action" disabled={busy===photo.asset_id||!urls[photo.asset_id]} onClick={()=>void openHd(photo)}><Eye size={16}/>{en?"HD":"高清"}</button><button className="secondary personal-album-action" disabled={busy===photo.asset_id||!urls[photo.asset_id]} onClick={()=>void save(photo)}><Download size={16}/>{busy===photo.asset_id?(en?"Preparing…":"准备中…"):(en?"Save":"保存")}</button></div><button className="text-button personal-album-remove" disabled={busy===photo.asset_id} onClick={()=>setDeleting(photo)}>{en?"Remove":"移出我的相册"}</button></article>)}</div></section>})}
    {hd&&<div className="photo-lightbox" role="dialog" aria-modal="true" aria-label={en?"HD photo":"高清照片"}><button className="icon-button photo-lightbox-close" aria-label={en?"Close HD photo":"关闭高清照片"} onClick={()=>setHd(null)}><X size={22}/></button><img src={hd.url} alt={hd.eventName}/></div>}{deleting&&<Confirm title={en?"Remove this photo from your album?":"移出我的参与赛事相册？"} description={en?"This deletes only your personal saved copy. The event source photo and other participants are not affected.":"只会删除你自己的个人相册副本，不影响赛事源照片，也不影响其他参赛者。"} onCancel={()=>setDeleting(null)} onConfirm={()=>void remove(deleting)}/>} 
  </main></>;
}
