import { Link, useParams } from "react-router-dom";
import { ArrowRight, Images } from "lucide-react";
import { Avatar, Empty, ErrorNotice, Header, Loading, levelLabel } from "../components/UI";
import { rpc } from "../repositories/supabase";
import { useQuery } from "../hooks/useQuery";
import { useLanguage } from "../i18n";

type PartnerProfile={id:string;nickname:string|null;avatar_url:string|null;player_id:string|null;level:string|null;city:string|null;play_times:string[];play_preference:"singles"|"doubles"|"both"|null};
type PartnerMatch={match_id:string;event_id:string;event_name:string;event_date:string|null;match_type:"singles"|"doubles";stage:string|null;round_no:number|null;won:boolean;opponents:{name:string;avatar_url:string|null}[]};
type PartnerDetail={profile:PartnerProfile;summary:{played:number;wins:number;losses:number};recent_matches:PartnerMatch[]}|null;
const timeLabel=(value:string,en:boolean)=>!en?value:value==="工作日白天"?"Weekday daytime":value==="工作日晚上"?"Weekday evenings":value==="周末白天"?"Weekend daytime":value==="周末晚上"?"Weekend evenings":value;
export function PartnerDetailPage(){
  const{profileId}=useParams();const{language,t}=useLanguage();const en=language==="en";const q=useQuery(`partner-detail-${profileId}`,()=>rpc<PartnerDetail>("get_connected_partner_profile",{p_profile_id:profileId}));
  const preferenceLabel=(value:string)=>value==="singles"?(en?"Prefers singles":"偏好单打"):value==="doubles"?(en?"Prefers doubles":"偏好双打"):(en?"Singles / doubles":"单打 / 双打都打");
  if(q.loading&&!q.data)return <><Header title={en?"Partner profile":"球搭子档案"}/><main className="page"><Loading/></main></>;
  if(!q.data)return <><Header title={en?"Partner profile":"球搭子档案"}/><main className="page"><ErrorNotice message={q.error} retry={q.refresh}/>{!q.error&&<Empty title={en?"This partner profile is not available":"暂时看不到这位球搭子的档案"}><p>{en?"Only people who have established a partner connection can view each other's profiles.":"只有已经建立球搭子关系的用户可以互相查看档案。"}</p></Empty>}</main></>;
  const{profile,summary,recent_matches}=q.data;const winRate=summary.played?Math.round(summary.wins/summary.played*100):0;const profileBits=[profile.level?levelLabel(profile.level,language):null,profile.city,profile.play_preference?preferenceLabel(profile.play_preference):null].filter(Boolean);
  return <><Header title={en?"Partner profile":"球搭子档案"}/><main className="page"><div className="profile-banner"><Avatar path={profile.avatar_url} name={profile.nickname||(en?"Partner":"球搭子")} size={72}/><div><span className="eyebrow">{en?"TENNIS PARTNER":"球场伙伴"}</span><h1>{profile.nickname||(en?"Partner":"球搭子")}</h1><p>{profileBits.length?profileBits.join(" · "):(en?"No additional tennis details yet":"还没有补充更多打球资料")}</p></div></div><ErrorNotice message={q.error} retry={q.refresh}/><div className="stats"><div><b>{summary.played}</b><small>{en?"Completed matches":"已完成比赛"}</small></div><div><b>{summary.wins}</b><small>{en?"Wins":"胜场"}</small></div><div><b>{summary.played?`${winRate}%`:"—"}</b><small>{en?"Win rate":"胜率"}</small></div></div><Link className="card row between" to={`/partners/${profileId}/albums`}><span className="row"><Images size={18}/>{en?"Shared past event albums":"TA 的比赛相册"}</span><ArrowRight size={18}/></Link><div className="card"><div className="section-heading"><h2>{en?"Tennis profile":"打球档案"}</h2></div><div className="event-facts"><div><small>{t("level")}</small><strong>{profile.level?levelLabel(profile.level,language):(en?"Not set":"未填写")}</strong></div><div><small>{t("city")}</small><strong>{profile.city||(en?"Not set":"未填写")}</strong></div><div><small>{en?"Preference":"偏好"}</small><strong>{profile.play_preference?preferenceLabel(profile.play_preference):(en?"Not set":"未填写")}</strong></div><div><small>{t("playTimes")}</small><strong>{profile.play_times?.length?profile.play_times.map(x=>timeLabel(x,en)).join(en?", ":"、"):(en?"Not set":"未填写")}</strong></div></div></div><div className="section-heading"><h2>{en?"Recent results":"最近战绩"}</h2><span className="muted small">{en?`${summary.wins} W · ${summary.losses} L`:`${summary.wins} 胜 · ${summary.losses} 负`}</span></div>{recent_matches.length?<div className="stack">{recent_matches.map(m=><Link className="card row between" key={m.match_id} to={`/events/${m.event_id}`}><div className="grow"><div className="row"><span className={m.won?"badge":"badge muted"}>{m.won?(en?"Win":"胜"):(en?"Loss":"负")}</span><strong>{m.event_name}</strong></div><p className="muted small">{m.event_date||(en?"Date TBD":"日期待定")} · {m.match_type==="doubles"?t("doubles"):t("singles")} · {en?"vs":"对阵"} {m.opponents.map(o=>o.name).join(" / ")||(en?"Opponent TBD":"对手待定")}</p></div><ArrowRight size={18}/></Link>)}</div>:<Empty title={en?"No completed matches yet":"还没有已完成的比赛"}><p>{en?"After an event is completed and results are recorded, recent matches will appear here.":"完成赛事并记录赛果后，这里会显示 TA 最近的比赛概况。"}</p></Empty>}</main></>;
}
