import { Header } from "../components/UI";
import { useLanguage } from "../i18n";

export function PrivacyNoticePage(){
  const{language}=useLanguage();const en=language==="en";
  return <><Header title={en?"Privacy Policy (Test Version)":"球搭子隐私政策（测试版）"} home={false}/><main className="page">
    <span className="eyebrow">{en?"CONTROLLED TEST BUILD":"受控测试版"}</span>
    <h1>{en?"Qiu Dazi Privacy Policy (Test Version)":"球搭子隐私政策（测试版）"}</h1>
    <p className="muted">{en?"Updated and effective: September 22, 2026":"更新及生效日期：2026年9月22日"}</p>
    <p>{en?"Welcome to Qiu Dazi. Qiu Dazi is currently independently developed and operated by an individual developer and remains a controlled test build. This policy explains how personal information may be processed during testing, why it is processed, how it may be displayed or stored, and how you may manage your information.":"欢迎使用“球搭子”。球搭子目前由个人开发者独立开发和运营，现阶段仍处于受控测试阶段。本政策用于说明测试期间我们可能处理哪些个人信息、为什么处理这些信息、相关信息如何展示和保存，以及你可以如何管理自己的个人信息。"}</p>

    <section className="settings-section"><h2>{en?"1. Who operates Qiu Dazi":"一、我们是谁"}</h2><p>{en?"Qiu Dazi is currently operated by an individual developer. Operator: [name / individual developer name]. Contact: [email]. If you have questions or wish to exercise personal-information rights, you may contact the operator through the above channel.":"球搭子当前由个人开发者运营。运营者：[姓名/个人开发者名称]。联系方式：[联系邮箱]。如你对本政策或个人信息处理有疑问，或者希望行使个人信息相关权利，可以通过上述方式联系我们。"}</p></section>

    <section className="settings-section"><h2>{en?"2. Personal information we may process":"二、我们可能处理的个人信息"}</h2>
      <p><strong>{en?"Test account and identity. ":"测试账号与身份信息。"}</strong>{en?"Your nickname, test-account identifiers, session identifiers and technical information necessary to maintain sign-in status. Nickname-based sign-in is used only for controlled testing and is not real-name verification.":"我们可能处理你的昵称、测试账号标识、登录会话标识以及维持登录状态所必要的技术信息。当前昵称登录机制仅用于受控测试，并非实名认证机制，也不用于证明用户的真实身份。"}</p>
      <p><strong>{en?"Tennis profile. ":"个人打球档案。"}</strong>{en?"Information you choose to provide, such as nickname, optional avatar, city, playing level, singles/doubles preference and preferred playing times.":"当你创建或完善个人打球档案时，我们可能处理你主动填写的昵称、头像、所在城市、网球水平、单双打偏好、常用打球时间等信息，其中头像为可选信息。"}</p>
      <p><strong>{en?"Event information. ":"赛事相关信息。"}</strong>{en?"Event name, time, venue, format, registration status, rosters, draws, scores, results and other information needed for event operation.":"当你创建、报名、参加或管理赛事时，我们可能处理赛事名称、赛事时间、比赛地点、赛事类型、报名情况、参赛名单、对阵信息、比赛比分、比赛结果以及与赛事管理有关的信息。"}</p>
      <p><strong>{en?"Partner relationships and invitations. ":"球搭子关系与邀请信息。"}</strong>{en?"Partner relationships, invitation sending and receiving records, invitation status and doubles-team information.":"当你使用添加球搭子、赛事邀请、双打组队邀请等功能时，我们可能处理球搭子关系、邀请发送与接收记录、邀请状态以及与组队有关的信息。"}</p>
      <p><strong>{en?"Event photos and personal event albums. ":"赛事照片及个人参赛相册信息。"}</strong>{en?"Only an event organizer can upload, manage or delete source photos for that event. Participants cannot upload, modify or delete source event photos. A participant may save or import a relevant photo from an event they actually participated in into their own personal event album, creating a personal copy that is independent from the source event photo. The participant manages that personal copy and its visibility. Deleting the source event photo does not automatically delete an already-created personal copy.":"在赛事照片功能中，只有赛事组织者可以上传、管理或删除本场赛事的赛事源照片。参赛者不能向赛事源相册上传、修改或删除赛事照片。对于自己实际参加的赛事，参赛者可以将赛事中的相关照片保存或导入至自己的“参与赛事相册”，形成与赛事源照片相互独立的个人相册副本。个人相册副本由对应参赛者自行管理，其可见范围按照个人隐私设置执行。赛事组织者后续删除赛事源照片，不会当然删除参赛者已经保存至个人参赛相册中的独立副本。"}</p>
      <p><strong>{en?"Privacy and feature preferences. ":"隐私及功能偏好。"}</strong>{en?"Profile-field visibility, whether you accept event or doubles invitations, and personal event-album visibility settings.":"我们可能处理头像、水平、城市、打球偏好等档案字段的可见范围，是否接受赛事或双打邀请，以及个人参赛相册的可见范围等设置。"}</p>
      <p><strong>{en?"Necessary technical information. ":"必要的技术信息。"}</strong>{en?"Browser local storage, session information, error information and request-related technical data that are necessary to keep the test service running and maintain sign-in status.":"为保障服务正常运行和维持登录状态，我们可能处理必要的浏览器本地存储、会话信息、错误信息以及网络请求相关技术信息。"}</p>
    </section>

    <section className="settings-section"><h2>{en?"3. Why we process this information":"三、我们为什么处理这些信息"}</h2><p>{en?"We use the above information to create and restore test identities, save and display tennis profiles, provide event creation and participation, roster and draw management, scoring and results, partner relationships and invitations, event-photo and personal-album features, saved privacy settings, service operation, troubleshooting and test-product improvement. We do not sell your personal information or use it for unrelated commercial advertising in the current test build.":"我们主要基于以下目的处理相关信息：创建和恢复测试身份；保存并展示打球档案；提供赛事创建、报名、名单管理、抽签、记分和赛果功能；提供球搭子关系、赛事邀请和双打组队功能；提供赛事源照片和个人参赛相册功能；保存隐私及功能偏好；保障测试版本正常运行、排查故障并改进产品体验。当前测试版本不会出售你的个人信息，也不会将其用于与上述目的无关的商业广告推送。"}</p></section>

    <section className="settings-section"><h2>{en?"4. Information that may be visible to other users":"四、哪些信息可能向其他用户展示"}</h2><p>{en?"Depending on event rules and your privacy settings, other users may see your nickname, avatar and selected tennis-profile fields, event rosters, draws, scores and results, and protected preview content from a personal event album that you have set as visible to accepted partners. Privacy settings control selected personal fields and personal-album visibility, but do not erase shared event facts such as rosters, scores or results.":"根据具体功能、赛事规则和你的隐私设置，其他用户可能看到你的昵称、头像及部分打球档案，赛事名单、对阵、比分和赛果，以及你设置为“球搭子可见”的个人参赛相册中的受保护预览内容。隐私设置主要控制个人档案字段和个人相册的展示范围，不会删除或隐藏已经形成的共同赛事事实，例如参赛名单、比赛比分和赛果。"}</p></section>

    <section className="settings-section"><h2>{en?"5. Storage and retention":"五、个人信息的存储"}</h2><p>{en?"Qiu Dazi currently uses an online shared test environment. During testing, information is retained only as needed for product functions, validation and necessary troubleshooting. Where information is deleted, cancelled or no longer needed, we will handle it according to the relevant product function, data relationships and system implementation, including deletion, anonymization or stopping further use where appropriate. Specific retention periods will be further defined before public operation.":"球搭子当前使用在线共享测试环境保存测试数据。在测试阶段，我们仅在实现产品功能、测试验证和必要问题排查所需的范围内保存相关信息。对于你删除、取消或不再需要的信息，我们会结合产品功能、数据关系和系统实现情况进行删除、匿名化处理或停止继续使用。正式公开运营前，我们将进一步明确不同类型个人信息的具体保存期限和删除规则。"}</p></section>

    <section className="settings-section"><h2>{en?"6. Third-party technical services":"六、第三方技术服务"}</h2><p>{en?"Qiu Dazi may use third-party cloud infrastructure for online databases, identity/session services, file storage and H5 deployment. Those service providers may process relevant data only to the extent necessary to provide their technical services. Before public operation, we will further identify service providers, purposes, data categories and relevant safeguards based on the actual production architecture.":"为实现在线数据库、身份认证、文件存储及 H5 页面部署等功能，球搭子目前可能使用第三方云服务和技术基础设施。相关服务商可能仅在提供技术服务所必要的范围内处理相应数据。正式公开运营前，我们会结合实际生产架构进一步明确相关服务商名称、处理目的、涉及的信息类型和保护措施。"}</p></section>

    <section className="settings-section"><h2>{en?"7. Your rights":"七、你的个人信息权利"}</h2><p>{en?"Within a reasonable scope, you may use product functions or contact us to request access, correction or supplementation, adjustment of profile or album visibility, deletion where applicable, an explanation of processing rules, or cessation of further use of relevant test data when you stop participating in testing. Some event information relates to other participants and shared event records, so requests involving rosters, scores or results may need to take account of other users' rights, event integrity and necessary record-keeping.":"在合理范围内，你可以通过产品功能或者联系我们，提出查询、更正或补充个人信息，调整个人档案和相册可见范围，删除符合删除条件的个人信息，了解个人信息处理规则，或者在不再继续测试时提出停止继续使用相关测试数据的请求。部分赛事信息同时涉及其他参赛者和共同赛事记录，因此涉及赛事名单、比分或赛果的请求，可能需要结合其他用户权益、赛事记录完整性和必要留存要求进行处理。"}</p></section>

    <section className="settings-section"><h2>{en?"8. Minors":"八、未成年人"}</h2><p>{en?"The current test build is primarily intended for adult users with independent civil capacity and does not currently provide features specifically designed for children under 14. If we become aware that personal information of a child under 14 has been processed without appropriate guardian authorization, we will take appropriate measures based on the circumstances, including stopping the processing or deleting the relevant information.":"球搭子当前测试版本主要面向具备独立民事行为能力的成年用户，目前未专门设计面向未满14周岁未成年人的产品功能。如我们发现存在未取得监护人适当授权而处理未满14周岁未成年人个人信息的情况，将根据实际情况采取停止处理、删除相关信息等措施。"}</p></section>

    <section className="settings-section"><h2>{en?"9. Information security":"九、信息安全"}</h2><p>{en?"We will use technical and organizational measures appropriate to the test stage, including authentication, access control, permission restrictions and necessary test-environment separation. However, no internet service is absolutely secure. Please do not submit information unrelated to testing, especially important passwords, identity documents, financial-account information, medical information or other highly sensitive information.":"我们会采取与测试阶段相适应的技术和管理措施保护个人信息，包括身份验证、访问控制、权限限制以及必要的测试环境隔离等措施。但互联网服务不存在绝对安全的技术环境，请不要在测试阶段提交与产品功能无关的重要账号密码、身份证件、金融账户、医疗健康信息或其他高度敏感信息。"}</p></section>

    <section className="settings-section"><h2>{en?"10. Special notice for the test build":"十、测试版本特别说明"}</h2><p>{en?"The current account model, infrastructure, features and data-processing methods may still change as testing continues. Before public operation, this policy will be further completed based on the actual operating model, including operator details, specific retention periods, third-party service disclosures, any cross-border processing, fuller rights-request channels, minors protections and other legally required disclosures. Material changes will be communicated through an appropriate notice.":"球搭子目前仍处于受控测试阶段，测试期间的账号体系、技术基础设施、产品功能和数据处理方式仍可能根据测试结果进行调整。正式面向公众提供服务前，我们会根据实际运营模式进一步完善本政策，包括运营者完整身份和联系方式、各类信息的具体保存期限、第三方服务情况、个人信息跨境情况、更完整的个人信息权利行使渠道、未成年人保护规则以及其他依法需要告知的事项。发生重大变化时，我们会通过页面提示或其他适当方式向你说明。"}</p></section>

    <section className="settings-section"><h2>{en?"11. Contact us":"十一、联系我们"}</h2><p>{en?"Operator: [name / individual developer name]. Contact email: [email]. We will review and respond to privacy-related requests within a reasonable period after receiving them.":"运营者：[姓名/个人开发者名称]。联系邮箱：[邮箱]。如你对个人信息保护、隐私设置或本政策有任何问题，可以通过上述方式联系我们；我们会在收到请求后，在合理期限内进行核实和处理。"}</p></section>

    <p className="notice">{en?"You can return to the previous page without signing in.":"你可以直接返回上一页，无需先登录。"}</p>
  </main></>;
}
