import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Avatar, ErrorNotice, Header } from "../components/UI";
import type { Event, Player } from "../domain/types";
import { command, explainError, repository, rpc } from "../repositories/supabase";
import { useLanguage } from "../i18n";

const PENDING_QUICK_DRAW_KEY="qiudazi-pending-quick-draw";
type PendingQuickDraw={id:string;version:number};
type QuickSource="self"|"connection"|"temporary";
type QuickPlayer=Player&{quick_source:QuickSource};
function localParts(){const d=new Date();const pad=(n:number)=>String(n).padStart(2,"0");return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`};}
function readPendingQuickDraw():PendingQuickDraw|null{try{const raw=sessionStorage.getItem(PENDING_QUICK_DRAW_KEY);if(!raw)return null;const parsed=JSON.parse(raw) as Partial<PendingQuickDraw>;return typeof parsed.id==="string"&&typeof parsed.version==="number"?{id:parsed.id,version:parsed.version}:null;}catch{return null;}}
function savePendingQuickDraw(value:PendingQuickDraw|null){try{if(value)sessionStorage.setItem(PENDING_QUICK_DRAW_KEY,JSON.stringify(value));else sessionStorage.removeItem(PENDING_QUICK_DRAW_KEY);}catch{}}

export function QuickStartPage(){
  const navigate=useNavigate();const{language}=useLanguage();const en=language==="en";
  const txt=(zh:string,english:string)=>en?english:zh;
  const [step,setStep]=useState(0),[matchType,setMatchType]=useState<"singles"|"doubles">("singles"),[players,setPlayers]=useState<QuickPlayer[]>([]),[selected,setSelected]=useState<string[]>([]),[pairing,setPairing]=useState<string[]>([]),[newName,setNewName]=useState(""),[city,setCity]=useState(""),[venue,setVenue]=useState(""),[format,setFormat]=useState<"round_robin"|"knockout">("round_robin"),[scoring,setScoring]=useState("games_6"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[pendingDraw,setPendingDraw]=useState<PendingQuickDraw|null>(()=>readPendingQuickDraw());
  useEffect(()=>{rpc<QuickPlayer[]>("list_quick_start_players").then(ps=>{setPlayers(ps);const self=ps.find(p=>p.quick_source==="self");if(self)setSelected([self.id]);}).catch(e=>setError(explainError(e)));},[]);
  useEffect(()=>{setSelected(()=>{const self=players.find(p=>p.quick_source==="self");return self?[self.id]:[];});setPairing([]);},[matchType]);
  const available=players;
  const orderedPlayers=matchType==="doubles"&&pairing.length===selected.length?pairing:selected;
  const entries=useMemo(()=>matchType==="singles"?selected.map(id=>[id]):Array.from({length:Math.floor(orderedPlayers.length/2)},(_,i)=>orderedPlayers.slice(i*2,i*2+2)),[matchType,selected,orderedPlayers]);
  const validSelection=matchType==="singles"?selected.length>=2:selected.length>=4&&selected.length%2===0;
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);setPairing([]);}
  function startPairing(){setPairing([...selected]);setStep(2);}
  function swapPairing(slot:number,nextId:string){setPairing(current=>{const next=[...current];const other=next.indexOf(nextId);if(other>=0)[next[slot],next[other]]=[next[other],next[slot]];else next[slot]=nextId;return next;});}
  async function addTemporary(){if(!newName.trim())return;setBusy(true);setError("");try{const p=await repository.savePlayer(null,newName.trim(),null);const quick={...p,quick_source:"temporary" as const};setPlayers(x=>[...x,quick]);setSelected(x=>[...x,p.id]);setPairing([]);setNewName("");}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  function openCreatedEvent(eventId:string){navigate(`/events/${eventId}?tab=draw`,{replace:true});}
  async function finishDraw(target:PendingQuickDraw){setBusy(true);setError("");try{await command(target.id,{type:"draw",event_version:target.version,confirmed:true});savePendingQuickDraw(null);setPendingDraw(null);openCreatedEvent(target.id);}catch(e){setError(explainError(e));setPendingDraw(target);savePendingQuickDraw(target);}finally{setBusy(false);}}
  async function create(){if(pendingDraw){await finishDraw(pendingDraw);return;}if(!validSelection)return;setBusy(true);setError("");try{const now=localParts();const created=await rpc<Event>("create_quick_event",{p_config:{match_type:matchType,format,scoring_type:scoring,city:city.trim()||null,venue:venue.trim()||null,event_date:now.date,event_time:now.time},p_entries:entries});const target={id:created.id,version:created.version};setPendingDraw(target);savePendingQuickDraw(target);try{await command(created.id,{type:"draw",event_version:created.version,confirmed:true});savePendingQuickDraw(null);setPendingDraw(null);openCreatedEvent(created.id);}catch(e){setError(explainError(e));}}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  const sourceLabel=(p:QuickPlayer)=>p.quick_source==="self"?txt("我","Me"):p.quick_source==="connection"?txt("球搭子","Partner"):txt("临时","Temporary");
  const setupStep=matchType==="doubles"?3:2;
  const dots=matchType==="doubles"?[0,1,2,3]:[0,1,2];
  return <><Header title={txt("快速开赛","Quick start")}/><main className="page quick-start-page"><span className="eyebrow">{txt("人已约好，直接开打","Players are ready")}</span><h1>{txt("快速开赛","Quick start")}</h1><p className="muted">{txt("不经过报名和候补，选好参赛者与双打队友后，一键创建赛事并自动生成对阵。","Skip registration and waitlists. Pick players and doubles teams, then create the event and draw automatically in one tap.")}</p><div className="quick-steps">{dots.map(dot=><span key={dot} className={step===dot?"active":""}>{dot+1}</span>)}</div><ErrorNotice message={error}/>
  {pendingDraw&&<section className="quick-card"><h2>{txt("开赛未完成","Start not completed")}</h2><p className="muted small">{txt("赛事已经创建，但自动生成对阵没有完成。恢复开赛只会继续完成这场赛事，不会重复创建。","The event was created, but automatic draw generation did not finish. Recovery continues this event only and will not create a duplicate.")}</p><div className="row"><button className="secondary grow" disabled={busy} onClick={()=>openCreatedEvent(pendingDraw.id)}>{txt("查看赛事","Open event")}</button><button className="grow" disabled={busy} onClick={()=>finishDraw(pendingDraw)}>{busy?txt("正在恢复…","Recovering…"):txt("恢复开赛","Recover start")}</button></div></section>}
  {!pendingDraw&&step===0&&<section className="quick-card"><h2>{txt("选择比赛类型","Choose match type")}</h2><div className="quick-choice-grid"><button className={matchType==="singles"?"quick-choice active":"quick-choice"} onClick={()=>setMatchType("singles")}><strong>{txt("单打","Singles")}</strong><small>1 vs 1</small></button><button className={matchType==="doubles"?"quick-choice active":"quick-choice"} onClick={()=>setMatchType("doubles")}><strong>{txt("双打","Doubles")}</strong><small>2 vs 2</small></button></div><button className="full" onClick={()=>setStep(1)}>{txt("选择参赛者","Choose players")}</button></section>}
  {!pendingDraw&&step===1&&<section className="quick-card"><h2>{txt("选择参赛者","Choose players")}</h2><p className="muted small">{matchType==="singles"?txt("至少选择 2 人。可以直接选择已连接的真实球搭子。","Choose at least 2 players. Connected partners can be selected directly."):txt("至少选择 4 人且人数为偶数。下一步会明确确认谁和谁是队友，不会直接按勾选顺序偷偷组队。","Choose at least 4 players and an even total. The next step explicitly confirms teammates instead of silently pairing by selection order.")}</p><div className="quick-player-list">{available.map(p=><button type="button" key={p.id} className={selected.includes(p.id)?"quick-player selected":"quick-player"} onClick={()=>toggle(p.id)}><Avatar path={p.avatar_url} name={p.name} size={36}/><span className="quick-player-copy">{p.name}<small>{sourceLabel(p)}</small></span><b>{selected.includes(p.id)?"✓":""}</b></button>)}</div><div className="quick-add"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder={txt("现场新增临时球搭子","Add a temporary player")}/><button type="button" disabled={busy||!newName.trim()} onClick={addTemporary}>＋</button></div><div className="row"><button className="secondary grow" onClick={()=>setStep(0)}>{txt("上一步","Back")}</button><button className="grow" disabled={!validSelection} onClick={()=>matchType==="doubles"?startPairing():setStep(setupStep)}>{matchType==="doubles"?txt("确认队友","Confirm teams"):txt("设置赛制","Match setup")}</button></div></section>}
  {!pendingDraw&&matchType==="doubles"&&step===2&&<section className="quick-card"><h2>{txt("确认双打队友","Confirm doubles teams")}</h2><p className="muted small">{txt("每张卡片是一支队伍。点击任一位置可与其他已选球员互换，确认后再进入赛制设置。","Each card is one team. Change either slot to swap with another selected player, then continue to match setup.")}</p><div className="quick-team-list">{entries.map((team,i)=><div className="quick-team-card" key={i}><strong>{txt(`第 ${i+1} 队`,`Team ${i+1}`)}</strong>{team.map((id,j)=><select key={j} value={id} onChange={e=>swapPairing(i*2+j,e.target.value)}>{selected.map(optionId=><option key={optionId} value={optionId}>{players.find(p=>p.id===optionId)?.name||optionId}</option>)}</select>)}</div>)}</div><div className="row"><button className="secondary grow" onClick={()=>setStep(1)}>{txt("重新选人","Reselect players")}</button><button className="grow" onClick={()=>setStep(3)}>{txt("确认队伍并继续","Confirm teams")}</button></div></section>}
  {!pendingDraw&&step===setupStep&&<section className="quick-card"><h2>{txt("设置赛制与计分","Match setup")}</h2><label>{txt("城市（可选）","City (optional)")}<input value={city} onChange={e=>setCity(e.target.value)} maxLength={30}/></label><label>{txt("场地（可选）","Venue (optional)")}<input value={venue} onChange={e=>setVenue(e.target.value)} maxLength={120}/></label><label>{txt("赛制","Format")}<select value={format} onChange={e=>setFormat(e.target.value as "round_robin"|"knockout")}><option value="round_robin">{txt("单循环","Round robin")}</option><option value="knockout">{txt("单淘汰","Knockout")}</option></select></label><label>{txt("比赛计分","Scoring")}<select value={scoring} onChange={e=>setScoring(e.target.value)}><option value="games_6">{txt("常用计分（6局制）","First to 6 games")}</option><option value="games_4">{txt("4局制","First to 4 games")}</option><option value="tiebreak_7">{txt("抢7","Tiebreak to 7")}</option><option value="points_11">{txt("抢11","First to 11")}</option></select></label>{matchType==="doubles"&&<div className="notice">{entries.map((team,i)=><div key={i}>{txt(`第 ${i+1} 队`,`Team ${i+1}`)} · {team.map(id=>players.find(p=>p.id===id)?.name).filter(Boolean).join(" / ")}</div>)}</div>}<p className="muted small">{txt("城市和场地都可以留空。点击“一键开赛”后，系统会创建赛事、锁定名单并自动生成对阵。","City and venue are optional. One tap creates the event, locks the roster and generates the draw automatically.")}</p><div className="row"><button className="secondary grow" onClick={()=>setStep(matchType==="doubles"?2:1)}>{txt("上一步","Back")}</button><button className="grow" disabled={busy||!validSelection} onClick={create}>{busy?txt("正在开赛…","Starting…"):txt("一键开赛","Start now")}</button></div></section>}
  </main></>;
}
