import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Avatar, ErrorNotice, Header } from "../components/UI";
import type { Event, Player } from "../domain/types";
import { command, explainError, repository, rpc } from "../repositories/supabase";
import { useLanguage } from "../i18n";

function localParts(){const d=new Date();const pad=(n:number)=>String(n).padStart(2,"0");return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`};}

export function QuickStartPage(){
  const navigate=useNavigate();const{language}=useLanguage();const en=language==="en";
  const txt=(zh:string,english:string)=>en?english:zh;
  const [step,setStep]=useState(0),[matchType,setMatchType]=useState<"singles"|"doubles">("singles"),[players,setPlayers]=useState<Player[]>([]),[selected,setSelected]=useState<string[]>([]),[newName,setNewName]=useState(""),[city,setCity]=useState(""),[venue,setVenue]=useState(""),[format,setFormat]=useState<"round_robin"|"knockout">("round_robin"),[scoring,setScoring]=useState("games_6"),[busy,setBusy]=useState(false),[error,setError]=useState("");
  useEffect(()=>{repository.players().then(ps=>{setPlayers(ps);const self=ps.find(p=>p.player_type==="self");if(self){setSelected([self.id]);if(self.city)setCity(self.city);}}).catch(e=>setError(explainError(e)));},[]);
  useEffect(()=>{setSelected(ids=>{const self=players.find(p=>p.player_type==="self");return self?[self.id]:[];});},[matchType]);
  const available=players.filter(p=>p.player_type==="self"||(p.player_type==="manual"&&!p.linked_user_id));
  const entries=useMemo(()=>matchType==="singles"?selected.map(id=>[id]):Array.from({length:Math.floor(selected.length/2)},(_,i)=>selected.slice(i*2,i*2+2)),[matchType,selected]);
  const validSelection=matchType==="singles"?selected.length>=2:selected.length>=4&&selected.length%2===0;
  function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
  async function addTemporary(){if(!newName.trim())return;setBusy(true);setError("");try{const p=await repository.savePlayer(null,newName.trim(),null);setPlayers(x=>[...x,p]);setSelected(x=>[...x,p.id]);setNewName("");}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  async function create(){if(!validSelection||!city.trim())return;setBusy(true);setError("");try{const now=localParts();const created=await rpc<Event>("create_quick_event",{p_config:{match_type:matchType,format,scoring_type:scoring,city:city.trim(),venue:venue.trim()||null,event_date:now.date,event_time:now.time},p_entries:entries});await command(created.id,{type:"draw",event_version:created.version,confirmed:true});navigate(`/events/${created.id}/manage`,{replace:true});}catch(e){setError(explainError(e));}finally{setBusy(false);}}
  return <><Header title={txt("快速开赛","Quick start")}/><main className="page quick-start-page"><span className="eyebrow">{txt("人已约好，直接开打","Players are ready")}</span><h1>{txt("快速开赛","Quick start")}</h1><p className="muted">{txt("不经过报名和候补，选好参赛者后直接生成对阵。","Skip registration and waitlists. Pick players and generate the draw immediately.")}</p><div className="quick-steps"><span className={step===0?"active":""}>1</span><span className={step===1?"active":""}>2</span><span className={step===2?"active":""}>3</span></div><ErrorNotice message={error}/>
  {step===0&&<section className="quick-card"><h2>{txt("选择比赛类型","Choose match type")}</h2><div className="quick-choice-grid"><button className={matchType==="singles"?"quick-choice active":"quick-choice"} onClick={()=>setMatchType("singles")}><strong>{txt("单打","Singles")}</strong><small>1 vs 1</small></button><button className={matchType==="doubles"?"quick-choice active":"quick-choice"} onClick={()=>setMatchType("doubles")}><strong>{txt("双打","Doubles")}</strong><small>2 vs 2</small></button></div><button className="full" onClick={()=>setStep(1)}>{txt("选择参赛者","Choose players")}</button></section>}
  {step===1&&<section className="quick-card"><h2>{txt("选择参赛者","Choose players")}</h2><p className="muted small">{matchType==="singles"?txt("至少选择 2 人。","Choose at least 2 players."):txt("至少选择 4 人，按勾选顺序每两人组成一队。","Choose at least 4 players. Every two selected players form a team in selection order.")}</p><div className="quick-player-list">{available.map(p=><button type="button" key={p.id} className={selected.includes(p.id)?"quick-player selected":"quick-player"} onClick={()=>toggle(p.id)}><Avatar path={p.avatar_url} name={p.name} size={36}/><span>{p.name}{p.player_type==="self"?<small>{txt("我","Me")}</small>:null}</span><b>{selected.includes(p.id)?"✓":""}</b></button>)}</div><div className="quick-add"><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder={txt("现场新增临时球搭子","Add a temporary player")}/><button type="button" disabled={busy||!newName.trim()} onClick={addTemporary}>＋</button></div>{matchType==="doubles"&&entries.length>0&&<div className="notice">{entries.map((team,i)=><div key={i}>{txt(`第 ${i+1} 队`,`Team ${i+1}`)} · {team.map(id=>players.find(p=>p.id===id)?.name).filter(Boolean).join(" / ")}</div>)}</div>}<div className="row"><button className="secondary grow" onClick={()=>setStep(0)}>{txt("上一步","Back")}</button><button className="grow" disabled={!validSelection} onClick={()=>setStep(2)}>{txt("设置赛制","Match setup")}</button></div></section>}
  {step===2&&<section className="quick-card"><h2>{txt("设置赛制与计分","Match setup")}</h2><label>{txt("城市 *","City *")}<input value={city} onChange={e=>setCity(e.target.value)} maxLength={30}/></label><label>{txt("场地（可选）","Venue (optional)")}<input value={venue} onChange={e=>setVenue(e.target.value)} maxLength={120}/></label><label>{txt("赛制","Format")}<select value={format} onChange={e=>setFormat(e.target.value as "round_robin"|"knockout")}><option value="round_robin">{txt("单循环","Round robin")}</option><option value="knockout">{txt("单淘汰","Knockout")}</option></select></label><label>{txt("比赛计分","Scoring")}<select value={scoring} onChange={e=>setScoring(e.target.value)}><option value="games_6">{txt("常用计分（6局制）","First to 6 games")}</option><option value="games_4">{txt("4局制","First to 4 games")}</option><option value="tiebreak_7">{txt("抢7","Tiebreak to 7")}</option><option value="points_11">{txt("抢11","First to 11")}</option></select></label><p className="muted small">{txt("创建后会直接锁定本场名单并自动生成对阵；开赛前仍可回到赛事管理调整。","The roster is locked and the draw is generated automatically. You can still adjust the event before play starts.")}</p><div className="row"><button className="secondary grow" onClick={()=>setStep(1)}>{txt("上一步","Back")}</button><button className="grow" disabled={busy||!city.trim()} onClick={create}>{busy?txt("正在生成…","Creating…"):txt("确认并生成对阵","Create draw")}</button></div></section>}
  </main></>;
}
