import { useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, X } from "lucide-react";
import { Empty, ErrorNotice, Header, Loading } from "./UI";
import { explainError, rpc } from "../repositories/supabase";
import { useQuery } from "../hooks/useQuery";
type EventInvite={id:string;event_id:string;event_name:string;event_date:string|null;city:string|null;venue:string|null;level:string|null;match_type:"singles"|"doubles";invite_kind:"event"|"doubles_partner";inviter_user_id:string;inviter_nickname:string|null;status:"pending"|"accepted"|"declined"|"cancelled"|"expired";created_at:string};
const loadInvites=()=>rpc<EventInvite[]>("list_my_event_invites");
export function EventInviteInboxLink(){const q=useQuery("my-event-invites",loadInvites);const pending=q.data?.filter(i=>i.status==="pending").length||0;return <Link className="card row between" to="/event-invites"><div><strong>赛事邀请{pending?` · ${pending} 条待回应`:""}</strong><p className="muted small">查看球搭子发给你的参赛或组队邀请</p></div><ArrowRight size={18}/></Link>}
export function EventInvitesPage(){const q=useQuery("my-event-invites",loadInvites);const[busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");async function respond(id:string,accept:boolean){setBusy(id);setError("");try{await rpc("respond_event_invite",{p_invite_id:id,p_accept:accept});await q.refresh()}catch(e){setError(explainError(e))}finally{setBusy(null)}}return <><Header title="赛事邀请"/><main className="page"><span className="eyebrow">EVENT INVITATIONS</span><h1>收到的邀请</h1><p className="muted">处理参赛和双打组队邀请。</p><ErrorNotice message={error||q.error} retry={q.refresh}/>{q.loading&&!q.data?<Loading/>:q.data?.length?<div className="stack">{q.data.map(i=>{const partner=i.invite_kind==="doubles_partner";const place=[i.city,i.venue].filter(Boolean).join(" · ")||"场地待定";const meta=[i.event_date||"日期待定",place,i.level?`${i.level}级`:null,partner?"双打组队":i.match_type==="doubles"?"双打":"单打"].filter(Boolean).join(" · ");return <article className="card event-invite-card" key={i.id}><p className="muted small">{i.inviter_nickname||"一位球搭子"}{partner?" 邀请你成为双打搭档":" 邀请你参加赛事"}</p><h3>{i.event_name}</h3><p className="muted small">{meta}</p>{i.status==="pending"?<div className="event-invite-actions"><button className="full" disabled={busy===i.id} onClick={()=>respond(i.id,true)}><Check size={16}/>{partner?"接受组队":"接受邀请"}</button><button className="secondary full" disabled={busy===i.id} onClick={()=>respond(i.id,false)}><X size={16}/>暂不参加</button></div>:i.status==="accepted"?partner?<p className="notice">已接受组队。等对方完成整队报名后，你们会一起进入参赛名单。</p>:<><p className="muted small">已接受邀请，还需要完成报名。</p><Link className="button full" to={`/events/${i.event_id}?join=1`}>去报名</Link></>:<p className="muted small">{i.status==="declined"?"已选择暂不参加":"邀请已结束"}</p>}<Link className="event-invite-detail-link" to={`/events/${i.event_id}`}>查看赛事 <ArrowRight size={15}/></Link></article>})}</div>:<Empty title="暂时没有赛事邀请"><p>当球搭子邀请你参赛或组队时，会出现在这里。</p></Empty>}</main></>}
