import { useEffect, useRef } from "react";
import type { ReactNode } from "react";
import { Link, NavLink, useNavigate } from "react-router-dom";
import { ArrowLeft, CalendarDays, Clock3, LockKeyhole, MapPin, Trophy, Users, UserRound, Flag, RefreshCw } from "lucide-react";
import type { Event, Entry } from "../domain/types";
import { assetUrl } from "../repositories/supabase";
import { useLanguage } from "../i18n";
export const labels: Record<string, string> = {signup:"报名中",locked:"已锁定",ongoing:"进行中",finished:"已结束",singles:"单打",doubles:"双打",round_robin:"单循环",knockout:"单淘汰",group_knockout:"小组 + 淘汰",games_4:"4局制",games_6:"6局制",tiebreak_7:"抢7",points_11:"抢11",points_15:"抢15",custom_games:"自定义局数"};
export function levelLabel(value?:string|null){if(!value)return "";if(value==="≤2.0")return "2.0及以下";if(value==="≥4.5")return "4.5及以上";return value;}
export function levelDisplay(value?:string|null){if(!value)return "";if(value==="≤2.0"||value==="≥4.5")return levelLabel(value);return `${levelLabel(value)}级`;}
export function suggestedLevelDisplay(min?:string|null,max?:string|null){if(!min&&!max)return "不限水平";if(min&&max&&min===max)return `建议 ${levelLabel(min)}`;if(!min&&max)return `建议 ${levelLabel(max)}及以下`.replace("及以下及以下","及以下");if(min&&!max)return `建议 ${levelLabel(min)}及以上`.replace("及以上及以上","及以上");return `建议 ${levelLabel(min)}–${levelLabel(max)}`;}
export function registrationText(e:Pick<Event,"status"|"registration_deadline">){if(e.status!=="signup")return e.status==="locked"?"报名已结束":"";if(!e.registration_deadline)return "";const end=new Date(e.registration_deadline);const ms=end.getTime()-Date.now();if(ms<=0)return "报名已截止";if(ms<3600000)return "报名即将截止";const hours=Math.ceil(ms/3600000);if(hours<=24)return `距报名截止约 ${hours} 小时`;return `报名截止 · ${String(end.getMonth()+1).padStart(2,"0")}月${String(end.getDate()).padStart(2,"0")}日 ${String(end.getHours()).padStart(2,"0")}:${String(end.getMinutes()).padStart(2,"0")}`;}
export function unit(e:Event){return e.match_type==="doubles"?"队":"人";}export function entryName(e:Entry|undefined){return e?e.team_name||e.players.map(p=>p.name).join(" / "):"待晋级";}export function feeText(e:Event,count=e.confirmed_count||0){if(e.fee_type==="free")return "免费";if(e.fee_type==="fixed")return "¥"+e.fixed_fee_per_entry+"/"+unit(e);const total=(e.venue_fee_total||0)+(e.ball_fee_total||0)+(e.other_fee_total||0);return count?"AA 预计 ¥"+(total/count).toFixed(2)+"/"+unit(e):"AA 总额 ¥"+total;}
export function Brand(){return <span className="brand"><i className="brand-mark"/><span>球搭子<small>TENNIS · TOGETHER</small></span></span>;}export function Avatar({path,name,size=48}:{path?:string|null;name?:string;size?:number}){return path?<img className="avatar" style={{width:size,height:size}} src={assetUrl(path)} alt={name||"参赛者头像"}/>:<span className="avatar fallback" style={{width:size,height:size}} aria-label="默认网球头像"><i/></span>;}export function Header({title,back=true,action}:{title:string;back?:boolean;action?:ReactNode}){const navigate=useNavigate();return <header className="topbar">{back?<button className="icon-button" aria-label="返回" onClick={()=>window.history.length>1?navigate(-1):navigate("/events")}><ArrowLeft size={21}/></button>:<span className="brand-mark small"/>}<strong>{title}</strong><span className="header-action">{action}</span></header>;}
export function BottomNav(){const{t}=useLanguage();return <nav className="bottom-nav" aria-label="主导航">{[["/events",t("hall"),Trophy],["/my-events",t("myEvents"),Flag],["/players",t("partners"),Users],["/me",t("me"),UserRound]].map(([url,label,Icon])=>{const I=Icon as typeof Trophy;return <NavLink end key={url as string} to={url as string}><I size={21}/><span>{label as string}</span></NavLink>;})}</nav>;}export function ErrorNotice({message,retry}:{message:string;retry?:()=>void}){return message?<div className="error" role="alert">{message}{retry&&<button className="text-button" onClick={retry}><RefreshCw size={15}/>重新加载</button>}</div>:null;}export function Loading(){return <div className="loading" role="status"><span/>正在连接球场…</div>;}export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><i className="court-mini"/><h3>{title}</h3>{children}</div>;}export function Sheet({title,open,onClose,children}:{title:string;open:boolean;onClose:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)ref.current?.showModal();else ref.current?.close();},[open]);return <dialog ref={ref} className="sheet" onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="sheet-content"><div className="sheet-handle"/><div className="row between"><h2>{title}</h2><button className="text-button" onClick={onClose}>关闭</button></div>{children}</div></dialog>;}export function Confirm({title,description,onConfirm,onCancel,busy=false}:{title:string;description:string;onConfirm:()=>void;onCancel:()=>void;busy?:boolean}){return <Sheet open title={title} onClose={onCancel}><p>{description}</p><div className="row"><button className="secondary grow" onClick={onCancel}>取消</button><button className="grow" disabled={busy} onClick={onConfirm}>{busy?"处理中…":"确认"}</button></div></Sheet>;}
export function EventCard({event:e,manage=false}:{event:Event;manage?:boolean}){const privatePreview=!manage&&e.visibility==="private"&&!e.event_date&&!e.owner_nickname;const href=privatePreview?`/events/${e.id}/preview`:"/events/"+e.id+(manage?"/manage":"");const level=suggestedLevelDisplay(e.suggested_level_min,e.suggested_level_max);const deadline=registrationText(e);return <Link className={"event-card"+(privatePreview?" private-event-card":"")} to={href}><div className="event-card-stripe"/><div className="row between"><span className={"badge "+e.status}>{labels[e.status]}</span><small className={privatePreview?"private-badge":""}>{privatePreview?<><LockKeyhole size={12}/> 私有赛事</>:<>{labels[e.match_type]} · {level}</>}</small></div><h3>{e.name}</h3>{privatePreview?<><p className="muted">{labels[e.match_type]} · {level} · {labels[e.format]}</p><div className="event-meta"><span><MapPin size={14}/>{e.city||"城市待定"}</span><span><LockKeyhole size={14}/>时间、具体场地与参与者仅向受邀球友开放</span></div><div className="private-event-foot">查看私有赛事预览</div></>:<><div className="row organizer-line"><Avatar path={e.owner_avatar_url} name={e.owner_nickname||"组织者"} size={24}/><span className="muted small"><b>{e.owner_nickname||"球搭子"}</b> · 组织者</span></div><p className="muted">{labels[e.format]} · {level} · {e.best_of===1?"一盘决胜":e.best_of===3?"三盘两胜":"五盘三胜"}</p><div className="event-meta"><span><CalendarDays size={14}/>{e.event_date||"日期待定"} {e.event_time?.slice(0,5)}</span><span><MapPin size={14}/>{e.city?`${e.city}${e.venue?` · ${e.venue}`:""}`:e.venue||"城市 / 场地待补充"}</span>{deadline&&<span className={deadline.includes("即将")||deadline.includes("约 1 ")?"deadline-soon":""}><Clock3 size={14}/>{deadline}</span>}</div><div className="card-bottom"><span><b>{e.confirmed_count??"—"}</b><small> / {e.entry_limit||"不限"} {unit(e)}</small></span><span className="fee">{feeText(e)}</span></div>{!!e.waitlist_count&&<small>候补 {e.waitlist_count}/2 {unit(e)}</small>}</>}</Link>;}
