from pathlib import Path
p=Path('src/pages/Basics.tsx')
s=p.read_text()
old='''        {mine && (\n          <>\n            <EventInviteInboxLink />\n            <Link className="card row between" to="/events/new">\n              <div>\n                <strong>创建新赛事</strong>\n                <p className="muted small">随时再发起一场单打或双打比赛</p>\n              </div>\n              <Plus size={20} />\n            </Link>\n          </>\n        )}\n        <div className="section-heading">\n          <h2>{mine ? "我的赛场" : "最近的比赛"}</h2>\n          <div className="row">\n            {mine && scope === "created" && (\n              <Link className="text-button" to="/events/new">\n                <Plus size={16} />\n                创建赛事\n              </Link>\n            )}\n            <button\n              className="text-button"\n              onClick={q.refresh}\n              aria-label="刷新赛事"\n            >\n              <RefreshCw size={16} />\n            </button>\n          </div>\n        </div>\n        {mine && (\n          <div className="chips">\n            <button\n              className={scope === "created" ? "active" : ""}\n              onClick={() => setScope("created")}\n            >\n              我创建的\n            </button>\n            <button\n              className={scope === "joined" ? "active" : ""}\n              onClick={() => setScope("joined")}\n            >\n              我参与的\n            </button>\n          </div>\n        )}'''
new='''        {mine && (\n          <div className="chips">\n            <button\n              className={scope === "created" ? "active" : ""}\n              onClick={() => { setScope("created"); setStatus(""); }}\n            >\n              我创建的\n            </button>\n            <button\n              className={scope === "joined" ? "active" : ""}\n              onClick={() => { setScope("joined"); setStatus(""); }}\n            >\n              我参与的\n            </button>\n          </div>\n        )}\n        {mine && scope === "joined" && <EventInviteInboxLink />}\n        <div className="section-heading">\n          <h2>{mine ? (scope === "created" ? "我创建的赛事" : "我参与的赛事") : "最近的比赛"}</h2>\n          <div className="row">\n            {mine && scope === "created" && (!!q.data?.length || !!status) && (\n              <Link className="text-button" to="/events/new">\n                <Plus size={16} />\n                创建赛事\n              </Link>\n            )}\n            <button\n              className="text-button"\n              onClick={q.refresh}\n              aria-label="刷新赛事"\n            >\n              <RefreshCw size={16} />\n            </button>\n          </div>\n        </div>'''
if old not in s: raise SystemExit('main My Events block not found')
s=s.replace(old,new,1)
old2='''            <Empty title={mine ? "还没有创建赛事" : "最近还没有符合条件的比赛"}>\n              <p>\n                {mine\n                  ? "召集搭子，开始一场自己的比赛。"\n                  : "调整筛选，或发起一场新的比赛。"}\n              </p>\n              <Link className="button" to="/events/new">\n                创建赛事\n              </Link>\n            </Empty>'''
new2='''            <Empty\n              title={\n                mine\n                  ? scope === "created"\n                    ? status ? "当前筛选下没有赛事" : "还没有创建赛事"\n                    : status ? "当前筛选下没有赛事" : "还没有参与赛事"\n                  : "最近还没有符合条件的比赛"\n              }\n            >\n              <p>\n                {mine\n                  ? scope === "created"\n                    ? status ? "换个赛事状态看看，或创建一场新的比赛。" : "召集搭子，开始一场自己的比赛。"\n                    : status ? "换个赛事状态看看。" : "报名或接受赛事邀请后，会出现在这里。"\n                  : "调整筛选，或发起一场新的比赛。"}\n              </p>\n              {mine && scope === "created" && !status && (\n                <Link className="button" to="/events/new">\n                  创建赛事\n                </Link>\n              )}\n              {!mine && (\n                <Link className="button" to="/events/new">\n                  创建赛事\n                </Link>\n              )}\n            </Empty>'''
if old2 not in s: raise SystemExit('empty block not found')
s=s.replace(old2,new2,1)
p.write_text(s)
