import { createContext, useContext, useMemo, useState, type ReactNode } from "react";
export type Language="zh-CN"|"en";
const KEY="qiudazi-language";
const dictionaries={
  "zh-CN":{
    hall:"赛事大厅",myEvents:"我的赛事",partners:"球搭子们",me:"我的",settings:"设置与隐私",language:"语言",privacy:"隐私",profileVisibility:"个人档案字段可见性",invites:"邀请设置",save:"保存设置",saved:"设置已保存",avatar:"头像",level:"水平级别",city:"常打城市",playTimes:"约球时间",playPreference:"单双打偏好",eventInvites:"允许球搭子向我发送赛事邀请",doublesInvites:"允许球搭子向我发送双打组队邀请",visibleHint:"这些设置控制球搭子浏览你的个人档案时能看到什么，不会隐藏赛事名单、比分和赛果等共同赛事事实。",testPrivacy:"当前仍为受控测试版。正式对外运营前会另行补充完整隐私政策、运营者信息和个人权利请求渠道。",
    signup:"报名中",locked:"已锁定",ongoing:"进行中",finished:"已结束",singles:"单打",doubles:"双打",roundRobin:"单循环",knockout:"单淘汰",groupKnockout:"小组 + 淘汰",unlimited:"不限",privateEvent:"私有赛事",registrationEnded:"报名已结束",registrationClosed:"报名已截止",registrationClosing:"报名即将截止",registrationDeadline:"报名截止",organizer:"组织者",free:"免费",
    filterEvents:"筛选赛事",hallHero:"下一场球，从这里开场。",hallHeroHint:"和球搭子，一起认真打场好球。",created:"我创建的",joined:"我参与的",createdEvents:"我创建的赛事",joinedEvents:"我参与的赛事",recentMatches:"最近的比赛",createEvent:"创建赛事",all:"全部",invitePartners:"喊球搭子一起来",noFilteredEvents:"当前筛选下没有赛事",noCreatedEvents:"还没有创建赛事",noJoinedEvents:"还没有参与赛事",noDiscoverableEvents:"暂时没有可发现赛事",createdEmptyHint:"召集搭子，开始一场自己的比赛。",createdFilteredHint:"换个赛事状态看看，或创建一场新的比赛。",joinedEmptyHint:"完成报名后，赛事会出现在这里。收到的邀请可以在上方查看。",joinedFilteredHint:"换个赛事状态看看。",hallEmptyHint:"现在还没有可以发现的比赛。可以稍后再来，或去“我的赛事”看看自己的比赛。",goMyEvents:"去我的赛事",suggestedLevelFilterHint:"参赛建议级别目前用于赛事信息展示，不作为硬性报名资格；本版暂不提供单值级别筛选，避免沿用旧“赛事级别”造成误导。",matchDate:"比赛日期",reset:"重置",viewEvents:"查看赛事",refreshEvents:"刷新赛事",
    myTennisProfile:"我的打球档案",myResults:"我的战绩",partnerInviteHistory:"球搭子邀请记录",syncing:"同步中",pendingRecovery:"待恢复",testIdentityNotice:"当前为受控测试版，昵称仅用于识别测试身份。",profileMotto:"每一场球，都值得认真对待。",
    match:"比赛",matchAdjusted:"比赛已调整",matchAdjustedHint:"这场比赛可能在重新生成签表后被替换，请返回赛事查看最新对阵。",viewEvent:"查看赛事",liveScoring:"实时记分",directScore:"直接录入比分",matchDetail:"比赛详情",bye:"轮空",notStarted:"未开始",round:"轮次",bestOf:"局制",matchEnded:"比赛结束",finalSetScore:"最终盘分",set:"盘",gameScore:"局分",point:"分",undoLastPoint:"撤销上一分",saving:"正在保存，请稍候…",liveSaved:"每一分实时保存到在线数据库。",traditionalAdvantage:"传统占先制",winByTwo:"领先2分获胜",recordedPoints:"已记录 {count} 分。",directScoreHint:"按实际盘分逐盘填写。发生抢七时需要填写抢七小分；比赛结束后的盘会自动禁用。",tiebreak:"抢七",formStale:"此比赛已被其他页面更新，当前表单版本已过期。请返回比赛详情后重新录入。",scoreSequenceError:"请按顺序完整填写每一盘的双方比分，不能跳过中间盘。",offTheCourt:"场外时光"
  },
  en:{
    hall:"Events",myEvents:"My Events",partners:"Partners",me:"Me",settings:"Settings & Privacy",language:"Language",privacy:"Privacy",profileVisibility:"Profile field visibility",invites:"Invitation settings",save:"Save settings",saved:"Settings saved",avatar:"Avatar",level:"Playing level",city:"Playing city",playTimes:"Preferred times",playPreference:"Singles / doubles preference",eventInvites:"Allow tennis partners to send me event invitations",doublesInvites:"Allow tennis partners to send me doubles team invitations",visibleHint:"These controls affect what partners can browse on your personal profile. They do not hide shared event facts such as rosters, scores or results.",testPrivacy:"This is still a controlled test build. A full privacy policy, operator information and rights-request channel will be added before public operation.",
    signup:"Registration open",locked:"Roster locked",ongoing:"In progress",finished:"Finished",singles:"Singles",doubles:"Doubles",roundRobin:"Round robin",knockout:"Knockout",groupKnockout:"Groups + knockout",unlimited:"Any level",privateEvent:"Private event",registrationEnded:"Registration ended",registrationClosed:"Registration closed",registrationClosing:"Registration closing soon",registrationDeadline:"Registration deadline",organizer:"Organizer",free:"Free",
    filterEvents:"Filter events",hallHero:"Your next match starts here.",hallHeroHint:"Play a good match with your tennis partners.",created:"Created",joined:"Joined",createdEvents:"Events I created",joinedEvents:"Events I joined",recentMatches:"Upcoming matches",createEvent:"Create event",all:"All",invitePartners:"Invite partners",noFilteredEvents:"No events match these filters",noCreatedEvents:"No events created yet",noJoinedEvents:"No events joined yet",noDiscoverableEvents:"No events to discover yet",createdEmptyHint:"Gather your partners and start a match of your own.",createdFilteredHint:"Try another event status, or create a new match.",joinedEmptyHint:"Events appear here after you complete registration. Invitations are available above.",joinedFilteredHint:"Try another event status.",hallEmptyHint:"There are no discoverable matches right now. Check back later or visit My Events.",goMyEvents:"Go to My Events",suggestedLevelFilterHint:"Suggested level is shown for discovery and is not an eligibility requirement. This version does not use the old single-level filter.",matchDate:"Match date",reset:"Reset",viewEvents:"View events",refreshEvents:"Refresh events",
    myTennisProfile:"My tennis profile",myResults:"My results",partnerInviteHistory:"Partner invitation history",syncing:"Syncing",pendingRecovery:"Recovering",testIdentityNotice:"This is a controlled test build. Nicknames are used only to identify test users.",profileMotto:"Every match deserves your best.",
    match:"Match",matchAdjusted:"Match updated",matchAdjustedHint:"This match may have been replaced after the draw was regenerated. Return to the event for the latest matchup.",viewEvent:"View event",liveScoring:"Live scoring",directScore:"Enter score",matchDetail:"Match details",bye:"Bye",notStarted:"Not started",round:"Round",bestOf:"Best of",matchEnded:"Match finished",finalSetScore:"Final set score",set:"Set",gameScore:"Games",point:"point",undoLastPoint:"Undo last point",saving:"Saving…",liveSaved:"Every point is saved to the online database.",traditionalAdvantage:"Advantage scoring",winByTwo:"Win by two",recordedPoints:"{count} points recorded.",directScoreHint:"Enter each set as played. Add tiebreak points when required; sets after the match is decided are disabled automatically.",tiebreak:"Tiebreak",formStale:"This match was updated elsewhere and this form is out of date. Return to match details and enter the score again.",scoreSequenceError:"Complete both scores for each set in order. Do not skip an earlier set.",offTheCourt:"OFF THE COURT"
  }
} as const;
type Key=keyof typeof dictionaries["zh-CN"];
const Ctx=createContext<{language:Language;setLanguage:(l:Language)=>void;t:(k:Key)=>string}>({language:"zh-CN",setLanguage:()=>{},t:k=>dictionaries["zh-CN"][k]});
export function LanguageProvider({children}:{children:ReactNode}){const[language,setState]=useState<Language>(()=>localStorage.getItem(KEY)==="en"?"en":"zh-CN");const value=useMemo(()=>({language,setLanguage:(l:Language)=>{localStorage.setItem(KEY,l);setState(l);},t:(k:Key)=>dictionaries[language][k]}),[language]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>;}
export function useLanguage(){return useContext(Ctx);}
