import { createContext, useContext, useMemo, useState, type ReactNode } from "react";
export type Language="zh-CN"|"en";
const KEY="qiudazi-language";
const dictionaries={
  "zh-CN":{
    hall:"赛事大厅",myEvents:"我的赛事",partners:"球搭子们",me:"我的",settings:"设置与隐私",language:"语言",privacy:"隐私",profileVisibility:"个人档案字段可见性",invites:"邀请设置",save:"保存设置",saved:"设置已保存",avatar:"头像",level:"水平级别",city:"常打城市",playTimes:"约球时间",playPreference:"单双打偏好",eventInvites:"允许球搭子向我发送赛事邀请",doublesInvites:"允许球搭子向我发送双打组队邀请",visibleHint:"这些设置控制球搭子浏览你的个人档案时能看到什么，不会隐藏赛事名单、比分和赛果等共同赛事事实。",testPrivacy:"当前仍为受控测试版。正式对外运营前会另行补充完整隐私政策、运营者信息和个人权利请求渠道。",
    signup:"报名中",locked:"已锁定",ongoing:"进行中",finished:"已结束",singles:"单打",doubles:"双打",roundRobin:"单循环",knockout:"单淘汰",groupKnockout:"小组 + 淘汰",unlimited:"不限",privateEvent:"私有赛事",registrationEnded:"报名已结束",registrationClosed:"报名已截止",registrationClosing:"报名即将截止",registrationDeadline:"报名截止",organizer:"组织者",free:"免费",
    filterEvents:"筛选赛事",hallHero:"下一场球，从这里开场。",hallHeroHint:"和球搭子，一起认真打场好球。",created:"我创建的",joined:"我参与的",createdEvents:"我创建的赛事",joinedEvents:"我参与的赛事",recentMatches:"最近的比赛",createEvent:"创建赛事",all:"全部",invitePartners:"喊球搭子一起来",noFilteredEvents:"当前筛选下没有赛事",noCreatedEvents:"还没有创建赛事",noJoinedEvents:"还没有参与赛事",noDiscoverableEvents:"暂时没有可发现赛事",createdEmptyHint:"召集搭子，开始一场自己的比赛。",createdFilteredHint:"换个赛事状态看看，或创建一场新的比赛。",joinedEmptyHint:"完成报名后，赛事会出现在这里。收到的邀请可以在上方查看。",joinedFilteredHint:"换个赛事状态看看。",hallEmptyHint:"现在还没有可以发现的比赛。可以稍后再来，或去“我的赛事”看看自己的比赛。",goMyEvents:"去我的赛事",suggestedLevelFilterHint:"参赛建议级别目前用于赛事信息展示，不作为硬性报名资格；本版暂不提供单值级别筛选，避免沿用旧“赛事级别”造成误导。",matchDate:"比赛日期",reset:"重置",viewEvents:"查看赛事",refreshEvents:"刷新赛事",
    myTennisProfile:"我的打球档案",myResults:"我的战绩",partnerInviteHistory:"球搭子邀请记录",syncing:"同步中",pendingRecovery:"待恢复",testIdentityNotice:"当前为受控测试版，昵称仅用于识别测试身份。",profileMotto:"每一场球，都值得认真对待。",
    inviteToEvent:"邀请球搭子参赛",inviteHero:"一起上场",inviteTitle:"喊球搭子一起来",inviteClosedHint:"这场赛事报名已经结束，不能再发送新的参赛邀请。",inviteOpenHint:"这是参赛邀请，不会给你赛事管理权限。对方接受后仍需要自己完成报名；单打不保证你们一定对阵。",partnerFallback:"球搭子",invitePending:"已邀请 · 等待回应",inviteAccepted:"已接受邀请",inviteDeclined:"之前暂不参加",inviteAgain:"可以重新邀请",myPartner:"我的球搭子",waiting:"等待中",accepted:"已接受",sending:"发送中…",closed:"已截止",invite:"邀请",noInvitablePartners:"还没有可以邀请的球搭子",noInvitablePartnersHint:"先在“球搭子们”建立关系，再邀请朋友一起参加公开赛事。",
    event:"赛事",eventManage:"赛事管理",eventDetail:"赛事详情",shareEvent:"分享赛事",shareCopied:"赛事链接已复制，可以发送给朋友",copyEventLink:"请复制此赛事链接：",confirmed:"正式",waitlist:"候补",generated:"已生成",notGenerated:"未生成",scheduleDraw:"赛程 / 签表",eventTab:"赛事",rosterTab:"参赛",drawTab:"对阵",rankingTab:"排名",photoTab:"合影",refresh:"刷新",venue:"球场",venueTbd:"场地待定",dateTbd:"日期待定",scoringRules:"计分规则",oneSet:"一盘决胜",bestOfThree:"三盘两胜",bestOfFive:"五盘三胜",fee:"费用",afterTiebreak:"后抢七",group:"个小组",topPerGroup:"每组前",advanceKnockout:"晋级淘汰赛",eventSettings:"赛事设置",eventSettingsHint:"修改时间、场地、赛制和报名设置",confirmedRoster:"正式名单",waitlistRoster:"候补名单",registration:"报名",continueRegistration:"请继续完成报名。",
    eventBasics:"赛事基础",eventName:"赛事名称 *",visibility:"赛事可见范围 *",publicFull:"公开 · 完整信息可见",privatePreview:"私有 · 大厅仅展示脱敏预览",visibilityHint:"公开赛事可查看完整公开信息并自主报名；私有赛事仍会在大厅出现，但只展示赛事名、城市、参赛建议级别、类型等基础信息。",matchType:"比赛类型",format:"赛制",suggestedMin:"参赛建议级别 · 最低",suggestedMax:"最高",suggestedHint:"这是帮助球友判断是否适合参加的建议区间，不是报名资格门槛。",matchRules:"比赛规则",sets:"盘数",scoringPerSet:"每盘计分",tiebreakTrigger:"抢七触发",targetGames:"目标局数 ≥1",scoringHint:"传统占先制。抢七和连续抢分均需领先2分。",groupCount:"小组数量",qualifiersPerGroup:"每组晋级名额",timeVenue:"时间与场地",entryLimit:"名额上限",startTime:"开赛时间 *",latestRegistration:"最晚报名时间 *",deadlineAdjusted:"比赛日期或开赛时间已调整，最晚报名时间已自动同步为当前允许的最晚时间。你仍可以继续提前截止。",deadlineRule:"默认开赛前2小时。可以提前截止，但不能晚于开赛前2小时。",currentLatest:"当前最晚可设为",eventCity:"城市 *",optionalVenue:"比赛场地（可选）",timeVenueHint:"公开赛事卡会显示比赛时间、城市、场地和报名截止状态；私有赛事大厅预览不公开具体时间与场地。",feeInfo:"费用说明",feeType:"费用类型",aa:"AA制",fixedFee:"固定费用",venueFee:"场地总费用（元）",ballFee:"用球总费用（元）",otherFee:"其他总费用（元）",estimatedTotal:"预计总费用",splitByParticipants:"按实际正式参赛人数均摊。",splitByTeams:"按实际正式参赛队伍均摊。",perPlayerFee:"每人费用（元）",perTeamFee:"每队费用（元）",feeHint:"费用仅展示，不提供在线支付和退款。",editEvent:"编辑赛事",eventSetup:"赛事设置",adjustMatch:"调整比赛安排",startGoodMatch:"发起一场好球",formHeroHint:"先集结球搭子，再锁定名单生成对阵。",continueSetup:"继续设置",deleteEmptyEvent:"删除空赛事",savingChanges:"保存中…",saveChanges:"保存修改",deleteEventTitle:"删除这场赛事？",deleteEventDescription:"仅报名中且没有任何报名历史的空赛事可删除，已有报名记录的赛事将被保护。",
    match:"比赛",matchAdjusted:"比赛已调整",matchAdjustedHint:"这场比赛可能在重新生成签表后被替换，请返回赛事查看最新对阵。",viewEvent:"查看赛事",liveScoring:"实时记分",directScore:"直接录入比分",matchDetail:"比赛详情",bye:"轮空",notStarted:"未开始",round:"轮次",bestOf:"局制",matchEnded:"比赛结束",finalSetScore:"最终盘分",set:"盘",gameScore:"局分",point:"分",undoLastPoint:"撤销上一分",saving:"正在保存，请稍候…",liveSaved:"每一分实时保存到在线数据库。",traditionalAdvantage:"传统占先制",winByTwo:"领先2分获胜",recordedPoints:"已记录 {count} 分。",directScoreHint:"按实际盘分逐盘填写。发生抢七时需要填写抢七小分；比赛结束后的盘会自动禁用。",tiebreak:"抢七",formStale:"这场比赛在你编辑期间发生了更新。为避免覆盖最新比分，请返回比赛详情后重新进入录分。 ",scoreSequenceError:"请按顺序完整填写每一盘的双方比分，不能跳过中间盘。",offTheCourt:"场外时光"
  },
  en:{
    hall:"Events",myEvents:"My Events",partners:"Partners",me:"Me",settings:"Settings & Privacy",language:"Language",privacy:"Privacy",profileVisibility:"Profile field visibility",invites:"Invitation settings",save:"Save settings",saved:"Settings saved",avatar:"Avatar",level:"Playing level",city:"Playing city",playTimes:"Preferred times",playPreference:"Singles / doubles preference",eventInvites:"Allow tennis partners to send me event invitations",doublesInvites:"Allow tennis partners to send me doubles team invitations",visibleHint:"These controls affect what partners can browse on your personal profile. They do not hide shared event facts such as rosters, scores or results.",testPrivacy:"This is still a controlled test build. A full privacy policy, operator information and rights-request channel will be added before public operation.",
    signup:"Registration open",locked:"Roster locked",ongoing:"In progress",finished:"Finished",singles:"Singles",doubles:"Doubles",roundRobin:"Round robin",knockout:"Knockout",groupKnockout:"Groups + knockout",unlimited:"Any level",privateEvent:"Private event",registrationEnded:"Registration ended",registrationClosed:"Registration closed",registrationClosing:"Registration closing soon",registrationDeadline:"Registration deadline",organizer:"Organizer",free:"Free",
    filterEvents:"Filter events",hallHero:"Your next match starts here.",hallHeroHint:"Play a good match with your tennis partners.",created:"Created",joined:"Joined",createdEvents:"Events I created",joinedEvents:"Events I joined",recentMatches:"Upcoming matches",createEvent:"Create event",all:"All",invitePartners:"Invite partners",noFilteredEvents:"No events match these filters",noCreatedEvents:"No events created yet",noJoinedEvents:"No events joined yet",noDiscoverableEvents:"No events to discover yet",createdEmptyHint:"Gather your partners and start a match of your own.",createdFilteredHint:"Try another event status, or create a new match.",joinedEmptyHint:"Events appear here after you complete registration. Invitations are available above.",joinedFilteredHint:"Try another event status.",hallEmptyHint:"There are no discoverable matches right now. Check back later or visit My Events.",goMyEvents:"Go to My Events",suggestedLevelFilterHint:"Suggested level is shown for discovery and is not an eligibility requirement. This version does not use the old single-level filter.",matchDate:"Match date",reset:"Reset",viewEvents:"View events",refreshEvents:"Refresh events",
    myTennisProfile:"My tennis profile",myResults:"My results",partnerInviteHistory:"Partner invitation history",syncing:"Syncing",pendingRecovery:"Recovering",testIdentityNotice:"This is a controlled test build. Nicknames are used only to identify test users.",profileMotto:"Every match deserves your best.",
    inviteToEvent:"Invite partners",inviteHero:"BRING YOUR TENNIS PEOPLE",inviteTitle:"Invite partners to play",inviteClosedHint:"Registration has ended, so new event invitations can no longer be sent.",inviteOpenHint:"This is an event invitation and does not grant event management access. The recipient still needs to register after accepting; singles invitations do not guarantee a matchup together.",partnerFallback:"Partner",invitePending:"Invited · awaiting response",inviteAccepted:"Invitation accepted",inviteDeclined:"Previously declined",inviteAgain:"Can invite again",myPartner:"My partner",waiting:"Waiting",accepted:"Accepted",sending:"Sending…",closed:"Closed",invite:"Invite",noInvitablePartners:"No partners available to invite",noInvitablePartnersHint:"Connect with someone in Partners first, then invite them to a public event.",
    event:"Event",eventManage:"Manage event",eventDetail:"Event details",shareEvent:"Share event",shareCopied:"Event link copied. You can send it to a friend.",copyEventLink:"Copy this event link: ",confirmed:"Confirmed",waitlist:"Waitlist",generated:"Generated",notGenerated:"Not generated",scheduleDraw:"Schedule / draw",eventTab:"Event",rosterTab:"Players",drawTab:"Draw",rankingTab:"Standings",photoTab:"Photo",refresh:"Refresh",venue:"Court",venueTbd:"Venue TBD",dateTbd:"Date TBD",scoringRules:"Scoring",oneSet:"One set",bestOfThree:"Best of 3",bestOfFive:"Best of 5",fee:"Fee",afterTiebreak:"then tiebreak",group:"groups",topPerGroup:"Top",advanceKnockout:"from each group advance to knockout",eventSettings:"Event settings",eventSettingsHint:"Update time, venue, format and registration settings",confirmedRoster:"Confirmed roster",waitlistRoster:"Waitlist",registration:"Registration",continueRegistration:"Continue to complete registration.",
    eventBasics:"Event basics",eventName:"Event name *",visibility:"Visibility *",publicFull:"Public · full details visible",privatePreview:"Private · limited preview in Events",visibilityHint:"Public events show full public details and allow normal registration. Private events remain discoverable but only show limited basics such as name, city, suggested level and type.",matchType:"Match type",format:"Format",suggestedMin:"Suggested level · minimum",suggestedMax:"Maximum",suggestedHint:"This range helps players judge fit. It is not an eligibility requirement.",matchRules:"Match rules",sets:"Sets",scoringPerSet:"Scoring per set",tiebreakTrigger:"Tiebreak trigger",targetGames:"Target games ≥1",scoringHint:"Advantage scoring. Tiebreaks and point races require a two-point lead.",groupCount:"Number of groups",qualifiersPerGroup:"Qualifiers per group",timeVenue:"Time & venue",entryLimit:"Entry limit",startTime:"Start time *",latestRegistration:"Registration deadline *",deadlineAdjusted:"The match date or start time changed, so the registration deadline was automatically moved to the latest allowed time. You can still close registration earlier.",deadlineRule:"Defaults to 2 hours before start. You may close earlier, but not later than 2 hours before start.",currentLatest:"Latest allowed:",eventCity:"City *",optionalVenue:"Venue (optional)",timeVenueHint:"Public event cards show match time, city, venue and registration status. Private previews do not reveal the exact time or venue.",feeInfo:"Fees",feeType:"Fee type",aa:"Split equally",fixedFee:"Fixed fee",venueFee:"Venue total",ballFee:"Ball total",otherFee:"Other total",estimatedTotal:"Estimated total",splitByParticipants:"Split across confirmed players.",splitByTeams:"Split across confirmed teams.",perPlayerFee:"Fee per player",perTeamFee:"Fee per team",feeHint:"Fees are display-only. Online payment and refunds are not included.",editEvent:"Edit event",eventSetup:"Event setup",adjustMatch:"Adjust match details",startGoodMatch:"Create a match",formHeroHint:"Bring players together, then lock the roster and generate the draw.",continueSetup:"Continue",deleteEmptyEvent:"Delete empty event",savingChanges:"Saving…",saveChanges:"Save changes",deleteEventTitle:"Delete this event?",deleteEventDescription:"Only an event still open for registration with no registration history can be deleted. Events with registration history are protected.",
    match:"Match",matchAdjusted:"Match updated",matchAdjustedHint:"This match may have been replaced after the draw was regenerated. Return to the event for the latest matchup.",viewEvent:"View event",liveScoring:"Live scoring",directScore:"Enter score",matchDetail:"Match details",bye:"Bye",notStarted:"Not started",round:"Round",bestOf:"Best of",matchEnded:"Match finished",finalSetScore:"Final set score",set:"Set",gameScore:"Games",point:"point",undoLastPoint:"Undo last point",saving:"Saving…",liveSaved:"Every point is saved to the online database.",traditionalAdvantage:"Advantage scoring",winByTwo:"Win by two",recordedPoints:"{count} points recorded.",directScoreHint:"Enter each set as played. Add tiebreak points when required; sets after the match is decided are disabled automatically.",tiebreak:"Tiebreak",formStale:"This match was updated elsewhere and this form is out of date. Return to match details and enter the score again.",scoreSequenceError:"Complete both scores for each set in order. Do not skip an earlier set.",offTheCourt:"OFF THE COURT"
  }
} as const;
type Key=keyof typeof dictionaries["zh-CN"];
const Ctx=createContext<{language:Language;setLanguage:(l:Language)=>void;t:(k:Key)=>string}>({language:"zh-CN",setLanguage:()=>{},t:k=>dictionaries["zh-CN"][k]});
export function LanguageProvider({children}:{children:ReactNode}){const[language,setState]=useState<Language>(()=>localStorage.getItem(KEY)==="en"?"en":"zh-CN");const value=useMemo(()=>({language,setLanguage:(l:Language)=>{localStorage.setItem(KEY,l);setState(l);},t:(k:Key)=>dictionaries[language][k]}),[language]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>;}
export function useLanguage(){return useContext(Ctx);}
