-- Applied to the shared Supabase test project on 2026-08-29.
-- Suggested level range replaces the event-facing single level. Legacy level is retained temporarily for compatibility.
alter table public.events add column if not exists suggested_level_min text, add column if not exists suggested_level_max text, add column if not exists registration_deadline timestamp without time zone;
update public.events set suggested_level_min=case when level='≤2.0' then null else level end, suggested_level_max=case when level='≥4.5' then null else level end where suggested_level_min is null and suggested_level_max is null and level is not null;
update public.events set registration_deadline=(event_date::timestamp+event_time)-interval '2 hours' where registration_deadline is null and event_date is not null and event_time is not null;
alter table public.events add constraint events_suggested_level_min_check check (suggested_level_min is null or suggested_level_min in ('≤2.0','2.5','3.0','3.5','4.0','≥4.5'));
alter table public.events add constraint events_suggested_level_max_check check (suggested_level_max is null or suggested_level_max in ('≤2.0','2.5','3.0','3.5','4.0','≥4.5'));
create table if not exists public.profile_preferences(profile_id uuid primary key references public.profiles(id) on delete cascade,avatar_visible boolean not null default true,level_visible boolean not null default true,city_visible boolean not null default true,play_times_visible boolean not null default true,play_preference_visible boolean not null default true,allow_event_invites boolean not null default true,allow_doubles_invites boolean not null default true,updated_at timestamptz not null default now());
alter table public.profile_preferences enable row level security;
create or replace function public.get_my_preferences() returns jsonb language plpgsql security definer set search_path='' as $$ declare me uuid:=public.current_profile_id(); p public.profile_preferences; begin if me is null then raise exception 'PROFILE_REQUIRED'; end if; insert into public.profile_preferences(profile_id) values(me) on conflict(profile_id) do nothing; select * into p from public.profile_preferences where profile_id=me; return to_jsonb(p); end $$;
create or replace function public.save_my_preferences(p_settings jsonb) returns jsonb language plpgsql security definer set search_path='' as $$ declare me uuid:=public.current_profile_id(); p public.profile_preferences; allowed text[]:=array['avatar_visible','level_visible','city_visible','play_times_visible','play_preference_visible','allow_event_invites','allow_doubles_invites']; begin if me is null then raise exception 'PROFILE_REQUIRED'; end if; if p_settings-allowed!='{}'::jsonb then raise exception 'INVALID_FIELDS'; end if; insert into public.profile_preferences(profile_id) values(me) on conflict(profile_id) do nothing; update public.profile_preferences set avatar_visible=coalesce((p_settings->>'avatar_visible')::boolean,avatar_visible),level_visible=coalesce((p_settings->>'level_visible')::boolean,level_visible),city_visible=coalesce((p_settings->>'city_visible')::boolean,city_visible),play_times_visible=coalesce((p_settings->>'play_times_visible')::boolean,play_times_visible),play_preference_visible=coalesce((p_settings->>'play_preference_visible')::boolean,play_preference_visible),allow_event_invites=coalesce((p_settings->>'allow_event_invites')::boolean,allow_event_invites),allow_doubles_invites=coalesce((p_settings->>'allow_doubles_invites')::boolean,allow_doubles_invites),updated_at=now() where profile_id=me returning * into p; return to_jsonb(p); end $$;
create or replace function public.event_registration_open(e public.events) returns boolean language sql stable set search_path='' as $$ select e.status='signup' and (e.registration_deadline is null or (now() at time zone 'Asia/Shanghai') < e.registration_deadline) $$;
create extension if not exists pg_cron with schema extensions;
create or replace function public.lock_expired_event_registrations() returns integer language plpgsql security definer set search_path='' as $$ declare n integer; begin update public.events set status='locked',version=version+1 where status='signup' and registration_deadline is not null and registration_deadline <= (now() at time zone 'Asia/Shanghai'); get diagnostics n=row_count; return n; end $$;
do $$ begin if not exists(select 1 from cron.job where jobname='lock-expired-event-registrations') then perform cron.schedule('lock-expired-event-registrations','*/5 * * * *','select public.lock_expired_event_registrations()'); end if; end $$;
